import { Injectable, Logger, Inject } from '@nestjs/common';
import type {
  IMemoryAdapter,
  AgentState,
  Store,
} from '@hive-academy/langgraph-core';
import type {
  AgentMemory,
  AgentMemoryContext,
  AgentMemoryStats,
  IAgentMemoryBridge,
  UserMemoryPatterns,
} from '../interfaces/agent-memory.interface';
import type { MemoryEntry } from '../interfaces/memory.interface';
import type { IVectorService } from '../interfaces/vector-service.interface';
import type { IGraphService } from '../interfaces/graph-service.interface';
import type { IStoreService } from '../store/services/interfaces/store-service.interface';
import { AgentMemoryCoreService } from './agent-memory-core.service';
import { AgentMemoryContextService } from './agent-memory-context.service';
import { AgentMemoryCheckpointService } from './agent-memory-checkpoint.service';
import { AgentMemoryStatsService } from './agent-memory-stats.service';

/**
 * Bridge service orchestrator for agent-memory integration
 *
 * REFACTORED: Reduced from 997 lines to orchestrator pattern
 *
 * Responsibility: IMemoryAdapter implementation + service orchestration
 * - Delegate CRUD operations to AgentMemoryCoreService
 * - Delegate context retrieval to AgentMemoryContextService
 * - Delegate checkpoint sync to AgentMemoryCheckpointService
 * - Delegate statistics to AgentMemoryStatsService
 * - Direct Store integration via IStoreService
 * - IMemoryAdapter compliance methods (9 wrappers)
 *
 * Pattern: Orchestrator delegates to specialized services
 * Architecture: Single Responsibility Principle - orchestration only
 *
 * TASK_2025_006: Split AgentMemoryBridgeService into Focused Services
 * - AgentMemoryCoreService: CRUD operations (252 lines)
 * - AgentMemoryContextService: Context retrieval (193 lines)
 * - AgentMemoryCheckpointService: Checkpoint sync (133 lines)
 * - AgentMemoryStatsService: Statistics tracking (104 lines)
 * - AgentMemoryBridgeService: Orchestrator (this file, ~200 lines)
 */
@Injectable()
export class AgentMemoryBridgeService
  implements IAgentMemoryBridge, IMemoryAdapter
{
  private readonly logger = new Logger(AgentMemoryBridgeService.name);

  constructor(
    private readonly coreService: AgentMemoryCoreService,
    private readonly contextService: AgentMemoryContextService,
    private readonly checkpointService: AgentMemoryCheckpointService,
    private readonly statsService: AgentMemoryStatsService,
    @Inject('IStoreService')
    private readonly storeService: IStoreService,
    @Inject('IVectorService')
    private readonly vectorService: IVectorService,
    @Inject('IGraphService')
    private readonly graphService: IGraphService
  ) {
    this.logger.log(
      'AgentMemoryBridge initialized (orchestrator pattern) with specialized services'
    );
  }

  // ========================================================================
  // IAgentMemoryBridge Implementation - Delegate to Specialized Services
  // ========================================================================

  /**
   * Get memory context for an agent during execution
   * Delegates to AgentMemoryContextService
   */
  async getAgentMemoryContext(
    agentId: string,
    threadId: string,
    query?: string,
    userId?: string
  ): Promise<AgentMemoryContext> {
    const context = await this.contextService.getAgentMemoryContext(
      agentId,
      threadId,
      query,
      userId
    );

    // Update statistics
    this.statsService.updateAgentStats(agentId, {
      memoriesAccessed: context.contextWindow,
    });

    return context;
  }

  /**
   * Store memory generated by an agent
   * Delegates to AgentMemoryCoreService
   */
  async storeAgentMemory(
    agentId: string,
    memory: AgentMemory
  ): Promise<MemoryEntry> {
    const storedMemory = await this.coreService.storeAgentMemory(
      agentId,
      memory
    );

    // Update statistics
    this.statsService.updateAgentStats(agentId, { memoriesCreated: 1 });

    return storedMemory;
  }

  /**
   * Store multiple agent memories in batch
   * Delegates to AgentMemoryCoreService
   */
  async storeAgentMemoriesBatch(
    agentId: string,
    memories: readonly AgentMemory[]
  ): Promise<readonly MemoryEntry[]> {
    const storedMemories = await this.coreService.storeAgentMemoriesBatch(
      agentId,
      memories
    );

    // Update statistics
    this.statsService.updateAgentStats(agentId, {
      memoriesCreated: storedMemories.length,
    });

    return storedMemories;
  }

  /**
   * Search for agent-specific memories
   * Delegates to AgentMemoryCoreService
   */
  async searchAgentMemories(
    agentId: string,
    query: string,
    options?: {
      readonly threadId?: string;
      readonly userId?: string;
      readonly limit?: number;
      readonly minRelevance?: number;
    }
  ): Promise<readonly MemoryEntry[]> {
    const startTime = Date.now();
    const memories = await this.coreService.searchAgentMemories(
      agentId,
      query,
      options
    );

    // Update statistics
    this.statsService.updateAgentStats(agentId, {
      searchTime: Date.now() - startTime,
    });

    return memories;
  }

  /**
   * Sync agent memories with checkpoint
   * Delegates to AgentMemoryCheckpointService
   */
  async syncWithCheckpoint(
    threadId: string,
    checkpointId: string,
    agentMemories?: readonly MemoryEntry[]
  ): Promise<void> {
    await this.checkpointService.syncWithCheckpoint(
      threadId,
      checkpointId,
      agentMemories
    );
  }

  /**
   * Get agent memory statistics
   * Delegates to AgentMemoryStatsService
   */
  async getAgentMemoryStats(agentId: string): Promise<AgentMemoryStats> {
    return this.statsService.getAgentMemoryStats(agentId);
  }

  /**
   * Clear agent memories for a thread
   * Delegates to AgentMemoryCoreService
   */
  async clearAgentMemories(agentId: string, threadId: string): Promise<number> {
    return this.coreService.clearAgentMemories(agentId, threadId);
  }

  // ========================================================================
  // Store Integration - Direct IStoreService Delegation
  // ========================================================================

  /**
   * Get the Store instance for cross-thread memory sharing
   * Provides hierarchical namespace-based storage
   *
   * Verification:
   * - Pattern source: phase-2-architecture.md:842-900
   * - Returns IStoreService (verified in store-service.interface.ts:5)
   * - Simple delegation pattern
   *
   * @param collection - Optional collection name (defaults to 'langgraph-stores')
   * @returns Store instance with put/get/search operations
   *
   * @example
   * ```typescript
   * const store = agentMemoryBridge.getStore();
   * await store.putStoreItem(['user', 'user-123', 'preferences'], 'theme', { mode: 'dark' });
   * ```
   */
  getStore(collection?: string): Store {
    if (collection) {
      this.logger.debug(`Creating scoped store for collection: ${collection}`);
      this.storeService.setDefaultCollection(collection);
    }

    // Return Store-compliant wrapper around IStoreService
    return {
      search: async (namespace: string[], query?: string) => {
        const filter = query ? { query } : undefined;
        return this.storeService.searchStoreItems(namespace, filter, 100);
      },
      get: async (namespace: string[], key: string) => {
        return this.storeService.getStoreItem(namespace, key);
      },
      put: async (
        namespace: string[],
        key: string,
        value: Record<string, any>
      ) => {
        await this.storeService.putStoreItem(namespace, key, value);
      },
      delete: async (namespace: string[], key: string) => {
        await this.storeService.deleteStoreItem(namespace, key);
      },
      list: async (namespace: string[]) => {
        const items = await this.storeService.searchStoreItems(
          namespace,
          undefined,
          1000
        );
        return items;
      },
    };
  }

  // ========================================================================
  // IMemoryAdapter Compliance Methods - Delegate to Specialized Services
  // ========================================================================
  // These methods provide thin wrappers for IMemoryAdapter interface compliance
  // All methods delegate to specialized services
  // Pattern source: implementation-plan.md:1417-1662

  /**
   * IMemoryAdapter compliance: Get agent context from state
   * Delegates to AgentMemoryContextService
   *
   * Pattern source: implementation-plan.md:1417-1432
   *
   * FIXED: Improved fallback handling with warnings when state is incomplete
   */
  async getAgentContext(state: AgentState): Promise<AgentMemoryContext> {
    // Extract agent ID with intelligent fallback
    const agentId = this.extractAgentId(state);
    const threadId = this.extractThreadId(state);

    // Warn if using fallback values (indicates upstream initialization issue)
    if (!state.current || !state.threadId) {
      this.logger.warn(
        'AgentState missing required properties for memory operations',
        {
          hasCurrent: !!state.current,
          hasThreadId: !!state.threadId,
          fallbackAgentId: agentId,
          fallbackThreadId: threadId,
          metadata: state.metadata,
        }
      );
    }

    return this.getAgentMemoryContext(
      agentId,
      threadId,
      state.messages?.[state.messages.length - 1]?.content,
      state.userId
    );
  }

  /**
   * Extract agent ID from state with intelligent fallback
   * Priority: state.current > metadata.networkId > 'default-agent'
   */
  private extractAgentId(state: AgentState): string {
    if (state.current) {
      return state.current;
    }

    // Try to extract from metadata
    const networkId = state.metadata?.networkId as string | undefined;
    if (networkId) {
      this.logger.debug(`Using networkId as fallback agentId: ${networkId}`);
      return networkId;
    }

    // Final fallback
    this.logger.warn('No agent ID found in state, using default-agent');
    return 'default-agent';
  }

  /**
   * Extract thread ID from state with intelligent fallback
   * Priority: state.threadId > generated from metadata > timestamp-based
   */
  private extractThreadId(state: AgentState): string {
    if (state.threadId) {
      return state.threadId;
    }

    // Try to generate from metadata
    const executionId = state.metadata?.executionId as string | undefined;
    const networkId = state.metadata?.networkId as string | undefined;

    if (executionId) {
      const fallbackThreadId = `thread-${executionId}`;
      this.logger.debug(
        `Generated fallback threadId from executionId: ${fallbackThreadId}`
      );
      return fallbackThreadId;
    }

    if (networkId) {
      const fallbackThreadId = `thread-${networkId}-${Date.now()}`;
      this.logger.debug(
        `Generated fallback threadId from networkId: ${fallbackThreadId}`
      );
      return fallbackThreadId;
    }

    // Final fallback with timestamp
    const fallbackThreadId = `thread-${Date.now()}`;
    this.logger.warn(
      `No thread identifier found in state, using timestamp-based fallback: ${fallbackThreadId}`
    );
    return fallbackThreadId;
  }

  /**
   * IMemoryAdapter compliance: Store agent execution result
   * Delegates to AgentMemoryCoreService
   *
   * Pattern source: implementation-plan.md:1434-1459
   */
  async storeAgentExecution(
    state: AgentState,
    result: Partial<AgentState>,
    agentId: string
  ): Promise<void> {
    const memory: AgentMemory = {
      content: JSON.stringify({
        input: state.messages?.[state.messages.length - 1]?.content,
        output: result.messages?.[result.messages.length - 1]?.content,
        timestamp: new Date().toISOString(),
      }),
      agentId,
      threadId: state.threadId || 'unknown',
      userId: state.userId,
      metadata: {
        agentGenerated: true as const,
        type: 'fact',
        memoryType: 'execution' as const,
        success: !result.metadata?.error,
        importance: result.metadata?.error ? 0.9 : 0.7,
      },
    };
    await this.storeAgentMemory(agentId, memory);
  }

  /**
   * IMemoryAdapter compliance: Store conversation turn
   * Delegates to AgentMemoryCoreService
   *
   * Pattern source: implementation-plan.md:1461-1486
   */
  async storeConversationTurn(
    threadId: string,
    humanMessage: string,
    aiMessage: string,
    metadata?: Record<string, unknown>
  ): Promise<void> {
    const turnId = `turn_${threadId}_${Date.now()}`;
    const agentId = (metadata?.agentId as string) || 'conversation-agent';
    const memories: AgentMemory[] = [
      {
        content: humanMessage,
        agentId,
        threadId,
        userId: metadata?.userId as string,
        metadata: {
          agentGenerated: true as const,
          memoryType: 'context' as const,
          type: 'conversation',
          role: 'human',
          turnId,
          ...metadata,
        },
      },
      {
        content: aiMessage,
        agentId,
        threadId,
        userId: metadata?.userId as string,
        metadata: {
          agentGenerated: true as const,
          memoryType: 'context' as const,
          type: 'conversation',
          role: 'assistant',
          turnId,
          ...metadata,
        },
      },
    ];
    await this.storeAgentMemoriesBatch(agentId, memories);
  }

  /**
   * IMemoryAdapter compliance: Generic search
   * Delegates to AgentMemoryCoreService or Store
   *
   * Pattern source: implementation-plan.md:1501-1532
   */
  async search(options: {
    query: string;
    threadId?: string;
    userId?: string;
    agentId?: string;
    limit?: number;
    namespace?: string[];
    minRelevance?: number;
  }): Promise<any[]> {
    if (options.namespace) {
      const store = this.getStore();
      return store.search(options.namespace, options.query);
    }
    const results = await this.searchAgentMemories(
      options.agentId || 'unknown',
      options.query,
      {
        threadId: options.threadId,
        userId: options.userId,
        limit: options.limit || 10,
        minRelevance: options.minRelevance || 0.5,
      }
    );
    return [...results]; // Convert readonly array to mutable
  }

  /**
   * IMemoryAdapter compliance: Store single memory
   * Delegates to AgentMemoryCoreService
   *
   * Pattern source: implementation-plan.md:1534-1554
   */
  async store(
    threadId: string,
    content: string,
    metadata?: Record<string, unknown>
  ): Promise<string> {
    const agentId = (metadata?.agentId as string) || 'unknown';
    const memory: AgentMemory = {
      content,
      agentId,
      threadId,
      userId: metadata?.userId as string,
      metadata: {
        agentGenerated: true as const,
        memoryType: 'context' as const,
        type: 'custom',
        ...metadata,
      },
    };
    const stored = await this.storeAgentMemory(agentId, memory);
    return stored.id;
  }

  /**
   * IMemoryAdapter compliance: Store batch of memories
   * Delegates to AgentMemoryCoreService
   *
   * Pattern source: implementation-plan.md:1556-1576
   */
  async storeBatch(
    threadId: string,
    entries: Array<{ content: string; metadata?: Record<string, unknown> }>
  ): Promise<string[]> {
    const agentId = (entries[0]?.metadata?.agentId as string) || 'unknown';
    const memories: AgentMemory[] = entries.map((entry) => ({
      content: entry.content,
      agentId: (entry.metadata?.agentId as string) || agentId,
      threadId,
      userId: entry.metadata?.userId as string,
      metadata: {
        agentGenerated: true as const,
        memoryType: 'context' as const,
        type: 'custom',
        ...entry.metadata,
      },
    }));
    const stored = await this.storeAgentMemoriesBatch(agentId, memories);
    return stored.map((m) => m.id);
  }

  /**
   * IMemoryAdapter compliance: Get user behavior patterns
   * Delegates to AgentMemoryContextService via graph or vector search
   *
   * Pattern source: implementation-plan.md:1578-1639
   */
  async getUserPatterns(
    userId: string,
    limitDays = 30
  ): Promise<UserMemoryPatterns> {
    if (!userId) {
      return {
        userId: 'unknown',
        commonTopics: [],
        interactionFrequency: {},
        preferredMemoryTypes: [],
        averageSessionLength: 0,
        totalSessions: 0,
      };
    }

    // Delegate to graph adapter if available
    if (
      this.graphService &&
      typeof (this.graphService as any).analyzeConversationPatterns ===
        'function'
    ) {
      try {
        return await (this.graphService as any).analyzeConversationPatterns(
          userId,
          limitDays
        );
      } catch (error) {
        this.logger.warn(
          `Graph pattern analysis failed, falling back to vector search: ${
            error instanceof Error ? error.message : String(error)
          }`
        );
      }
    }

    // Fallback to context service's pattern extraction
    // Use context service's method via a new context retrieval
    const context = await this.contextService.getAgentMemoryContext(
      'pattern-extraction',
      'temp',
      undefined,
      userId
    );

    return context.userPatterns;
  }

  /**
   * IMemoryAdapter compliance: Health check
   * Verifies vector and graph adapter health
   *
   * Pattern source: implementation-plan.md:1641-1662
   */
  async isHealthy(): Promise<boolean> {
    try {
      // Test vector adapter
      if (
        this.vectorService &&
        typeof this.vectorService.getStats === 'function'
      ) {
        await this.vectorService.getStats('vector-memories');
      }
      // Test graph adapter (optional)
      if (
        this.graphService &&
        typeof this.graphService.getStats === 'function'
      ) {
        await this.graphService.getStats();
      }
      return true;
    } catch (error) {
      this.logger.error(
        `Health check failed: ${
          error instanceof Error ? error.message : String(error)
        }`
      );
      return false;
    }
  }
}
