import { Injectable, Logger, Inject } from '@nestjs/common';
import { NodeIdBuilder } from '@hive-academy/langgraph-core';
import type { AgentMemory } from '../interfaces/agent-memory.interface';
import type { MemoryEntry } from '../interfaces/memory.interface';
import type { IVectorService } from '../interfaces/vector-service.interface';
import type { IGraphService } from '../interfaces/graph-service.interface';
import { wrapMemoryError } from '../errors/memory.errors';

/**
 * Core CRUD operations for agent memories
 *
 * Responsibility: Single-purpose service for agent memory storage and retrieval
 * - Store single agent memory (with vector + graph coordination)
 * - Store batch agent memories (optimized batch operations)
 * - Search agent memories (namespace-filtered semantic search)
 * - Clear agent memories (dual storage cleanup)
 *
 * Pattern: Direct vector/graph service coordination with graceful degradation
 * Verification: Extracted from AgentMemoryBridgeService lines 196-571
 */
@Injectable()
export class AgentMemoryCoreService {
  private readonly logger = new Logger(AgentMemoryCoreService.name);

  constructor(
    @Inject('IVectorService')
    private readonly vectorService: IVectorService,
    @Inject('IGraphService')
    private readonly graphService: IGraphService
  ) {
    this.logger.log('AgentMemoryCoreService initialized');
  }

  /**
   * Store memory generated by an agent with proper attribution
   *
   * Verification:
   * - Pattern source: phase-2-architecture.md:442-552
   * - Uses vectorService.storeMemory() (verified in vector-service.interface.ts:93)
   * - Uses graphService.trackMemory() (verified in graph-service.interface.ts:85)
   * - Dual storage coordination (vector primary, graph secondary)
   * - Namespace format: agent:${agentId} (preserved from original)
   *
   * @param agentId - Agent identifier for namespace isolation
   * @param memory - Agent memory to store
   * @returns Stored memory entry with ID
   */
  async storeAgentMemory(
    agentId: string,
    memory: AgentMemory
  ): Promise<MemoryEntry> {
    try {
      this.logger.debug(
        `Storing memory from agent ${agentId}: ${memory.content.slice(
          0,
          50
        )}...`
      );

      // Create canonical thread ID for agent memory
      const agentThreadId = NodeIdBuilder.create()
        .domain('agent')
        .phase('memory')
        .activity(agentId)
        .detail(memory.threadId)
        .build();

      // Enhance metadata with agent information
      const enhancedMetadata = {
        ...memory.metadata,
        agentGenerated: true as const,
        agentId,
        source: `agent-${agentId}`,
        namespace: `agent:${agentId}`,
        createdByAgent: true,
      };

      // Direct vectorService call for vector storage
      const storedMemory = await this.vectorService.storeMemory(
        agentThreadId,
        memory.content,
        enhancedMetadata,
        memory.userId
      );

      // Direct graphService call for graph tracking (graceful degradation)
      try {
        await this.graphService.trackMemory(storedMemory);
      } catch (graphError) {
        this.logger.warn(
          `Graph tracking failed (graceful degradation): ${
            graphError instanceof Error
              ? graphError.message
              : String(graphError)
          }`
        );
      }

      this.logger.debug(`✅ Agent memory stored: ${storedMemory.id}`);
      return storedMemory;
    } catch (error) {
      this.logger.error(
        `Failed to store agent memory: ${
          error instanceof Error ? error.message : String(error)
        }`
      );
      throw wrapMemoryError('storeAgentMemory', error);
    }
  }

  /**
   * Store multiple agent memories in batch
   *
   * Verification:
   * - Pattern source: phase-2-architecture.md:563-720
   * - Uses vectorService.storeMemoriesBatch() (verified in vector-service.interface.ts:116)
   * - Uses graphService.trackMemoriesBatch() (verified in graph-service.interface.ts:91)
   * - Dual storage coordination with batch operations
   * - Namespace format: agent:${agentId} (preserved for all memories)
   *
   * @param agentId - Agent identifier for namespace isolation
   * @param memories - Array of agent memories to store
   * @returns Array of stored memory entries with IDs
   */
  async storeAgentMemoriesBatch(
    agentId: string,
    memories: readonly AgentMemory[]
  ): Promise<readonly MemoryEntry[]> {
    if (memories.length === 0) return [];

    try {
      this.logger.debug(
        `Batch storing ${memories.length} memories from agent ${agentId}`
      );

      // Group memories by thread for efficient storage
      const memoriesByThread = new Map<string, AgentMemory[]>();

      for (const memory of memories) {
        const agentThreadId = NodeIdBuilder.create()
          .domain('agent')
          .phase('memory')
          .activity(agentId)
          .detail(memory.threadId)
          .build();

        if (!memoriesByThread.has(agentThreadId)) {
          memoriesByThread.set(agentThreadId, []);
        }
        memoriesByThread.get(agentThreadId)!.push(memory);
      }

      // Store memories for each thread
      const storedMemories: MemoryEntry[] = [];

      for (const [agentThreadId, threadMemories] of memoriesByThread) {
        const batchEntries = threadMemories.map((memory) => ({
          content: memory.content,
          metadata: {
            ...memory.metadata,
            agentGenerated: true as const,
            agentId,
            source: `agent-${agentId}`,
            namespace: `agent:${agentId}`,
            createdByAgent: true,
          },
        }));

        // Direct vectorService batch call
        const batchResults = await this.vectorService.storeMemoriesBatch(
          agentThreadId,
          batchEntries,
          threadMemories[0]?.userId
        );

        storedMemories.push(...batchResults);
      }

      // Batch track in graph database (graceful degradation)
      try {
        await this.graphService.trackMemoriesBatch(storedMemories);
      } catch (graphError) {
        this.logger.warn(
          `Graph batch tracking failed (graceful degradation): ${
            graphError instanceof Error
              ? graphError.message
              : String(graphError)
          }`
        );
      }

      this.logger.debug(
        `✅ Batch stored ${storedMemories.length} agent memories`
      );
      return storedMemories;
    } catch (error) {
      this.logger.error(
        `Failed to batch store agent memories: ${
          error instanceof Error ? error.message : String(error)
        }`
      );
      throw wrapMemoryError('storeAgentMemoriesBatch', error);
    }
  }

  /**
   * Search for memories created by a specific agent
   *
   * Verification:
   * - Pattern source: phase-2-architecture.md:732-835
   * - Uses vectorService.searchMemoriesSimilar() (verified in vector-service.interface.ts:156)
   * - Namespace format: agent:${agentId} (preserved from original)
   * - Graceful degradation: Returns empty array on error
   *
   * @param agentId - Agent identifier for namespace filtering
   * @param query - Search query text
   * @param options - Search options (threadId, userId, limit, minRelevance)
   * @returns Array of matching memory entries
   */
  async searchAgentMemories(
    agentId: string,
    query: string,
    options?: {
      readonly threadId?: string;
      readonly userId?: string;
      readonly limit?: number;
      readonly minRelevance?: number;
    }
  ): Promise<readonly MemoryEntry[]> {
    try {
      // Build filter object for vectorService
      const filter: Record<string, unknown> = {
        agentId, // Agent-specific filter
        namespace: `agent:${agentId}`, // Namespace filter
      };

      // Add optional filters
      if (options?.threadId) {
        filter.threadId = options.threadId;
      }
      if (options?.userId) {
        filter.userId = options.userId;
      }

      // Direct vectorService search with semantic similarity
      const memories = await this.vectorService.searchMemoriesSimilar(
        query,
        filter,
        options?.limit || 10
      );

      // Filter by relevance threshold (if provided)
      const filteredMemories = options?.minRelevance
        ? memories.filter((mem) => {
            const score =
              typeof mem.metadata.relevanceScore === 'number'
                ? mem.metadata.relevanceScore
                : 0;
            return score >= options.minRelevance!;
          })
        : memories;

      this.logger.debug(
        `Found ${filteredMemories.length} memories for agent ${agentId}`
      );

      return filteredMemories;
    } catch (error) {
      this.logger.error(
        `Failed to search agent memories: ${
          error instanceof Error ? error.message : String(error)
        }`
      );
      return [];
    }
  }

  /**
   * Clear all memories for an agent in a specific thread
   *
   * Verification:
   * - Pattern source: phase-2-architecture.md:847-953
   * - Uses vectorService.deleteMemories() (verified in vector-service.interface.ts:173)
   * - Uses graphService.deleteMemories() (verified in graph-service.interface.ts:97)
   * - Dual storage coordination with graceful degradation
   * - Namespace format preserved: agent:${agentId}
   *
   * @param agentId - Agent identifier for namespace filtering
   * @param threadId - Thread identifier for scoped deletion
   * @returns Number of memories deleted
   */
  async clearAgentMemories(agentId: string, threadId: string): Promise<number> {
    try {
      this.logger.debug(
        `Clearing memories for agent ${agentId} in thread ${threadId}`
      );

      // Get agent memories for this thread
      const agentMemories = await this.searchAgentMemories(agentId, '', {
        threadId,
        limit: 1000, // Get all memories
      });

      if (agentMemories.length === 0) {
        return 0;
      }

      const memoryIds = agentMemories.map((m) => m.id);

      // Delete from vector storage
      const deletedCount = await this.vectorService.deleteMemories(memoryIds);

      // Delete from graph storage (graceful degradation)
      try {
        await this.graphService.deleteMemories(memoryIds);
      } catch (graphError) {
        this.logger.warn(
          `Graph deletion failed (graceful degradation): ${
            graphError instanceof Error
              ? graphError.message
              : String(graphError)
          }`
        );
      }

      this.logger.debug(
        `✅ Cleared ${deletedCount} memories for agent ${agentId}`
      );
      return deletedCount;
    } catch (error) {
      this.logger.error(
        `Failed to clear agent memories: ${
          error instanceof Error ? error.message : String(error)
        }`
      );
      return 0;
    }
  }
}
