import { Injectable, Logger, Optional, Inject } from '@nestjs/common';
import { NodeIdBuilder } from '@hive-academy/langgraph-core';
import type { ICheckpointAdapter } from '@hive-academy/langgraph-core';
import type {
  AgentMemory,
  AgentMemoryContext,
  AgentMemoryStats,
  IAgentMemoryBridge,
  UserMemoryPatterns,
} from '../interfaces/agent-memory.interface';
import type {
  MemoryEntry,
  UserMemoryPatterns as ReadonlyUserMemoryPatterns,
} from '../interfaces/memory.interface';
import { MemoryService } from './memory.service';
import { wrapMemoryError } from '../errors/memory.errors';

/**
 * Bridge service that enables agent-memory integration
 *
 * This service provides:
 * ✅ Memory context retrieval for agents during execution
 * ✅ Agent-generated memory storage with proper attribution
 * ✅ Checkpoint coordination for memory persistence
 * ✅ Agent-specific memory analytics and monitoring
 * ✅ Memory namespace management for agent isolation
 */
@Injectable()
export class AgentMemoryBridgeService implements IAgentMemoryBridge {
  private readonly logger = new Logger(AgentMemoryBridgeService.name);
  private readonly agentStats = new Map<string, AgentMemoryStats>();

  constructor(
    private readonly memoryService: MemoryService,
    @Optional()
    @Inject('ICheckpointAdapter')
    private readonly checkpointAdapter?: ICheckpointAdapter
  ) {
    this.logger.log(
      'AgentMemoryBridge initialized with memory and checkpoint services'
    );
  }

  /**
   * Get comprehensive memory context for an agent during execution
   */
  async getAgentMemoryContext(
    agentId: string,
    threadId: string,
    query?: string,
    userId?: string
  ): Promise<AgentMemoryContext> {
    const startTime = Date.now();

    try {
      this.logger.debug(
        `Getting memory context for agent ${agentId} in thread ${threadId}`
      );

      // Search for relevant memories with agent-specific namespace
      const searchResults = await this.memoryService.searchForContext(
        query || `agent context for ${agentId}`,
        threadId,
        userId
      );

      // Include agent-specific memories (memories created by this agent)
      const agentSpecificMemories = await this.searchAgentMemories(
        agentId,
        query || '',
        {
          threadId,
          userId,
          limit: 5,
          minRelevance: 0.6,
        }
      );

      // Combine all relevant memories
      const allMemories = [
        ...searchResults.relevantMemories,
        ...agentSpecificMemories.filter(
          // Avoid duplicates
          (agentMem) =>
            !searchResults.relevantMemories.some(
              (mem) => mem.id === agentMem.id
            )
        ),
      ];

      // Categorize memories by type
      const threadMemories = allMemories.filter(
        (m) => m.metadata?.threadId === threadId
      );
      const userMemories = allMemories.filter(
        (m) =>
          m.metadata?.userId === agentId && m.metadata?.threadId !== threadId
      );
      const agentMemoriesFiltered = allMemories.filter(
        (m) => m.metadata?.agentId === agentId
      );

      // Calculate combined confidence
      const confidence = searchResults.confidence;

      // Update agent statistics
      this.updateAgentStats(agentId, {
        memoriesAccessed: allMemories.length,
        searchTime: Date.now() - startTime,
      });

      const context: AgentMemoryContext = {
        threadMemories: threadMemories,
        userMemories: userMemories,
        agentMemories: agentMemoriesFiltered,
        userPatterns: this.convertToMutableUserPatterns(
          searchResults.userPatterns
        ) || {
          userId: agentId || 'unknown',
          commonTopics: [],
          interactionFrequency: {},
          preferredMemoryTypes: [],
          averageSessionLength: 0,
          totalSessions: 0,
          lastInteraction: undefined,
        },
        relevanceScore: confidence,
        contextWindow: allMemories.length,
      };

      this.logger.debug(
        `Retrieved ${allMemories.length} memories for agent ${agentId} (confidence: ${confidence})`
      );

      return context;
    } catch (error) {
      this.logger.error(
        `Failed to get memory context for agent ${agentId}: ${
          error instanceof Error ? error.message : String(error)
        }`
      );

      // Return empty context on failure (graceful degradation)
      return {
        threadMemories: [],
        userMemories: [],
        agentMemories: [],
        userPatterns: {
          userId: agentId || 'unknown',
          commonTopics: [],
          interactionFrequency: {},
          preferredMemoryTypes: [],
          averageSessionLength: 0,
          totalSessions: 0,
          lastInteraction: undefined,
        } as UserMemoryPatterns,
        relevanceScore: 0,
        contextWindow: 0,
      };
    }
  }

  /**
   * Store memory generated by an agent with proper attribution
   */
  async storeAgentMemory(
    agentId: string,
    memory: AgentMemory
  ): Promise<MemoryEntry> {
    try {
      this.logger.debug(
        `Storing memory from agent ${agentId}: ${memory.content.slice(
          0,
          50
        )}...`
      );

      // Create canonical thread ID for agent memory
      const agentThreadId = NodeIdBuilder.create()
        .domain('agent')
        .phase('memory')
        .activity(agentId)
        .detail(memory.threadId)
        .build();

      // Enhance metadata with agent information
      const enhancedMetadata = {
        ...memory.metadata,
        agentGenerated: true as const,
        agentId,
        source: `agent-${agentId}`,
        namespace: `agent:${agentId}`,
        createdByAgent: true,
      };

      // Store in memory system
      const storedMemory = await this.memoryService.store(
        agentThreadId,
        memory.content,
        enhancedMetadata,
        memory.userId
      );

      // Update agent statistics
      this.updateAgentStats(agentId, { memoriesCreated: 1 });

      this.logger.debug(`✅ Agent memory stored: ${storedMemory.id}`);
      return storedMemory;
    } catch (error) {
      this.logger.error(
        `Failed to store agent memory: ${
          error instanceof Error ? error.message : String(error)
        }`
      );
      throw wrapMemoryError('storeAgentMemory', error);
    }
  }

  /**
   * Store multiple agent memories in batch
   */
  async storeAgentMemoriesBatch(
    agentId: string,
    memories: readonly AgentMemory[]
  ): Promise<readonly MemoryEntry[]> {
    if (memories.length === 0) return [];

    try {
      this.logger.debug(
        `Batch storing ${memories.length} memories from agent ${agentId}`
      );

      // Group memories by thread for efficient storage
      const memoriesByThread = new Map<string, AgentMemory[]>();

      for (const memory of memories) {
        const agentThreadId = NodeIdBuilder.create()
          .domain('agent')
          .phase('memory')
          .activity(agentId)
          .detail(memory.threadId)
          .build();

        if (!memoriesByThread.has(agentThreadId)) {
          memoriesByThread.set(agentThreadId, []);
        }
        memoriesByThread.get(agentThreadId)!.push(memory);
      }

      // Store memories for each thread
      const storedMemories: MemoryEntry[] = [];

      for (const [agentThreadId, threadMemories] of memoriesByThread) {
        const batchEntries = threadMemories.map((memory) => ({
          content: memory.content,
          metadata: {
            ...memory.metadata,
            agentGenerated: true as const,
            agentId,
            source: `agent-${agentId}`,
            namespace: `agent:${agentId}`,
            createdByAgent: true,
          },
        }));

        const batchResults = await this.memoryService.storeBatch(
          agentThreadId,
          batchEntries,
          threadMemories[0]?.userId
        );

        storedMemories.push(...batchResults);
      }

      // Update agent statistics
      this.updateAgentStats(agentId, {
        memoriesCreated: storedMemories.length,
      });

      this.logger.debug(
        `✅ Batch stored ${storedMemories.length} agent memories`
      );
      return storedMemories;
    } catch (error) {
      this.logger.error(
        `Failed to batch store agent memories: ${
          error instanceof Error ? error.message : String(error)
        }`
      );
      throw wrapMemoryError('storeAgentMemoriesBatch', error);
    }
  }

  /**
   * Search for memories created by a specific agent
   */
  async searchAgentMemories(
    agentId: string,
    query: string,
    options?: {
      readonly threadId?: string;
      readonly userId?: string;
      readonly limit?: number;
      readonly minRelevance?: number;
    }
  ): Promise<readonly MemoryEntry[]> {
    try {
      const searchOptions = {
        query,
        threadId: options?.threadId,
        userId: options?.userId,
        limit: options?.limit || 10,
        minRelevance: options?.minRelevance || 0.5,
        // Filter for agent-generated memories
        tags: [`agent:${agentId}`],
        type: 'custom' as const,
      };

      const memories = await this.memoryService.search(searchOptions);

      // Additional filtering for agent-specific memories
      const agentMemories = memories.filter(
        (memory) => memory.metadata.agentId === agentId
      );

      this.logger.debug(
        `Found ${agentMemories.length} memories for agent ${agentId}`
      );

      return agentMemories;
    } catch (error) {
      this.logger.error(
        `Failed to search agent memories: ${
          error instanceof Error ? error.message : String(error)
        }`
      );
      return [];
    }
  }

  /**
   * Sync agent memories with checkpoint for coordinated persistence
   */
  async syncWithCheckpoint(
    threadId: string,
    checkpointId: string,
    agentMemories?: readonly MemoryEntry[]
  ): Promise<void> {
    if (!this.checkpointAdapter) {
      this.logger.debug(
        'No checkpoint adapter available - skipping memory sync'
      );
      return;
    }

    try {
      this.logger.debug(
        `Syncing memories with checkpoint ${checkpointId} for thread ${threadId}`
      );

      // Get checkpoint metadata
      const checkpoint = await this.checkpointAdapter.loadCheckpoint(
        threadId,
        checkpointId
      );

      if (!checkpoint) {
        this.logger.warn(
          `Checkpoint ${checkpointId} not found for thread ${threadId}`
        );
        return;
      }

      // Create memory-checkpoint link metadata
      const syncMetadata = {
        checkpointId,
        threadId,
        syncedAt: new Date().toISOString(),
        memoryCount: agentMemories?.length || 0,
      };

      // Store sync information in checkpoint metadata
      await this.checkpointAdapter.saveCheckpoint(
        threadId,
        checkpoint.channel_values,
        {
          timestamp: new Date().toISOString(),
          source: 'update' as const,
          step: 0,
          parents: {},
          memorySync: syncMetadata,
        }
      );

      // If agent memories provided, ensure they're linked to this checkpoint
      if (agentMemories && agentMemories.length > 0) {
        await this.linkMemoriesToCheckpoint(agentMemories, checkpointId);
      }

      this.logger.debug(`✅ Memory-checkpoint sync completed for ${threadId}`);
    } catch (error) {
      this.logger.error(
        `Failed to sync memories with checkpoint: ${
          error instanceof Error ? error.message : String(error)
        }`
      );
      // Don't throw - sync failures shouldn't break agent execution
    }
  }

  /**
   * Get memory usage statistics for an agent
   */
  async getAgentMemoryStats(agentId: string): Promise<AgentMemoryStats> {
    const stats = this.agentStats.get(agentId);

    if (!stats) {
      return {
        agentId,
        memoriesAccessed: 0,
        memoriesCreated: 0,
        averageSearchTime: 0,
        contextHitRate: 0,
        lastAccess: new Date(),
      };
    }

    return stats;
  }

  /**
   * Clear all memories for an agent in a specific thread
   */
  async clearAgentMemories(agentId: string, threadId: string): Promise<number> {
    try {
      this.logger.debug(
        `Clearing memories for agent ${agentId} in thread ${threadId}`
      );

      // Create agent thread ID
      const agentThreadId = NodeIdBuilder.create()
        .domain('agent')
        .phase('memory')
        .activity(agentId)
        .detail(threadId)
        .build();

      // Get agent memories for this thread
      const agentMemories = await this.searchAgentMemories(agentId, '', {
        threadId,
        limit: 1000, // Get all memories
      });

      if (agentMemories.length === 0) {
        return 0;
      }

      // Delete memories
      const deletedCount = await this.memoryService.delete(
        agentThreadId,
        agentMemories.map((m) => m.id)
      );

      this.logger.debug(
        `✅ Cleared ${deletedCount} memories for agent ${agentId}`
      );
      return deletedCount;
    } catch (error) {
      this.logger.error(
        `Failed to clear agent memories: ${
          error instanceof Error ? error.message : String(error)
        }`
      );
      return 0;
    }
  }

  // Private helper methods

  /**
   * Update agent memory statistics
   */
  private updateAgentStats(
    agentId: string,
    updates: {
      memoriesAccessed?: number;
      memoriesCreated?: number;
      searchTime?: number;
    }
  ): void {
    const currentStats = this.agentStats.get(agentId) || {
      agentId,
      memoriesAccessed: 0,
      memoriesCreated: 0,
      averageSearchTime: 0,
      contextHitRate: 0.85,
      lastAccess: new Date(),
    };

    const newStats: AgentMemoryStats = {
      agentId,
      memoriesAccessed:
        currentStats.memoriesAccessed + (updates.memoriesAccessed || 0),
      memoriesCreated:
        currentStats.memoriesCreated + (updates.memoriesCreated || 0),
      averageSearchTime: updates.searchTime
        ? (currentStats.averageSearchTime + updates.searchTime) / 2
        : currentStats.averageSearchTime,
      contextHitRate: currentStats.contextHitRate,
      lastAccess: new Date(),
    };

    this.agentStats.set(agentId, newStats);
  }

  /**
   * Link memories to a specific checkpoint
   */
  private async linkMemoriesToCheckpoint(
    memories: readonly MemoryEntry[],
    checkpointId: string
  ): Promise<void> {
    // This could be implemented by updating memory metadata
    // or creating separate relationship tracking
    this.logger.debug(
      `Linking ${memories.length} memories to checkpoint ${checkpointId}`
    );

    // For now, we log the association
    // In a full implementation, this could update memory metadata
    // or create a separate relationship table/collection
  }

  /**
   * Convert readonly UserMemoryPatterns to mutable version
   */
  private convertToMutableUserPatterns(
    readonlyPatterns: ReadonlyUserMemoryPatterns | null
  ): UserMemoryPatterns | null {
    if (!readonlyPatterns) {
      return null;
    }

    return {
      userId: readonlyPatterns.userId,
      commonTopics: [...readonlyPatterns.commonTopics],
      interactionFrequency: { ...readonlyPatterns.interactionFrequency },
      preferredMemoryTypes: [...readonlyPatterns.preferredMemoryTypes],
      averageSessionLength: readonlyPatterns.averageSessionLength,
      totalSessions: readonlyPatterns.totalSessions,
      lastInteraction: undefined, // agent-memory interface doesn't have this field
    };
  }
}
