import type { MemoryEntry, MemoryMetadata } from './memory.interface';

/**
 * Memory context provided to agents during execution
 */
export interface AgentMemoryContext {
  readonly threadId: string;
  readonly agentId: string;
  readonly relevantMemories: readonly MemoryEntry[];
  readonly userPatterns?: {
    readonly commonTopics: readonly string[];
    readonly interactionFrequency: Record<string, number>;
    readonly preferredMemoryTypes: readonly string[];
  };
  readonly confidence: number;
  readonly lastUpdated: Date;
}

/**
 * Memory entry specifically created by agents
 */
export interface AgentMemory {
  readonly content: string;
  readonly agentId: string;
  readonly threadId: string;
  readonly metadata: Partial<MemoryMetadata> & {
    readonly agentGenerated: true;
    readonly nodeId?: string;
    readonly executionId?: string;
  };
  readonly userId?: string;
}

/**
 * Configuration for agent memory access
 */
export interface AgentMemoryConfig {
  readonly enabled: boolean;
  readonly scope: 'thread' | 'user' | 'global';
  readonly retention: 'session' | 'persistent';
  readonly searchLimit: number;
  readonly namespace?: string;
  readonly minRelevance?: number;
}

/**
 * Memory statistics for agent monitoring
 */
export interface AgentMemoryStats {
  readonly memoriesAccessed: number;
  readonly memoriesCreated: number;
  readonly averageSearchTime: number;
  readonly contextHitRate: number;
  readonly lastAccess: Date;
}

/**
 * Bridge service interface for agent-memory integration
 */
export interface IAgentMemoryBridge {
  /**
   * Get memory context for an agent during execution
   */
  getAgentMemoryContext(
    agentId: string,
    threadId: string,
    query?: string,
    userId?: string
  ): Promise<AgentMemoryContext>;

  /**
   * Store memory generated by an agent
   */
  storeAgentMemory(agentId: string, memory: AgentMemory): Promise<MemoryEntry>;

  /**
   * Store multiple memories in batch from agent
   */
  storeAgentMemoriesBatch(
    agentId: string,
    memories: readonly AgentMemory[]
  ): Promise<readonly MemoryEntry[]>;

  /**
   * Search for agent-specific memories
   */
  searchAgentMemories(
    agentId: string,
    query: string,
    options?: {
      readonly threadId?: string;
      readonly userId?: string;
      readonly limit?: number;
      readonly minRelevance?: number;
    }
  ): Promise<readonly MemoryEntry[]>;

  /**
   * Sync agent memories with checkpoint
   */
  syncWithCheckpoint(
    threadId: string,
    checkpointId: string,
    agentMemories?: readonly MemoryEntry[]
  ): Promise<void>;

  /**
   * Get agent memory statistics
   */
  getAgentMemoryStats(agentId: string): Promise<AgentMemoryStats>;

  /**
   * Clear agent memories for a thread
   */
  clearAgentMemories(agentId: string, threadId: string): Promise<number>;
}
