/**
 * @fileoverview Simple Test Example for New Repository Decorator
 *
 * This file demonstrates that the new repository decorator compiles
 * and can be used without TypeScript errors.
 */

import { Injectable } from '@nestjs/common';
import type { BaseDocument } from '../../types/core.interface';
import type { ChromaDBService } from '../../services/chromadb.service';
import { ChromaRepository } from './repository-decorator';
import type { ChromaRepository as ChromaRepositoryInterface } from './repository-metadata';

// Define a test document type
type TestDocument = BaseDocument<{
  category: string;
  priority: number;
  tags: string[];
}>;

// Create a test repository using the new decorator
@Injectable()
@ChromaRepository<TestDocument>({
  collection: 'test-documents',
  autoEmbed: true,
  enableCaching: true,
  enableValidation: true,
  autoTimestamp: true,
  autoGenerateIds: true,
  errorHandling: 'throw',
})
export class TestDocumentRepository
  implements ChromaRepositoryInterface<TestDocument>
{
  constructor(private readonly chromaService: ChromaDBService) {}

  // All CRUD methods are auto-generated by the decorator
  create!: ChromaRepositoryInterface<TestDocument>['create'];
  createMany!: ChromaRepositoryInterface<TestDocument>['createMany'];
  findById!: ChromaRepositoryInterface<TestDocument>['findById'];
  findByIds!: ChromaRepositoryInterface<TestDocument>['findByIds'];
  findAll!: ChromaRepositoryInterface<TestDocument>['findAll'];
  update!: ChromaRepositoryInterface<TestDocument>['update'];
  updateMany!: ChromaRepositoryInterface<TestDocument>['updateMany'];
  upsert!: ChromaRepositoryInterface<TestDocument>['upsert'];
  upsertMany!: ChromaRepositoryInterface<TestDocument>['upsertMany'];
  delete!: ChromaRepositoryInterface<TestDocument>['delete'];
  deleteMany!: ChromaRepositoryInterface<TestDocument>['deleteMany'];
  deleteByFilter!: ChromaRepositoryInterface<TestDocument>['deleteByFilter'];
  search!: ChromaRepositoryInterface<TestDocument>['search'];
  searchWithScores!: ChromaRepositoryInterface<TestDocument>['searchWithScores'];
  searchSimilar!: ChromaRepositoryInterface<TestDocument>['searchSimilar'];
  count!: ChromaRepositoryInterface<TestDocument>['count'];
  exists!: ChromaRepositoryInterface<TestDocument>['exists'];
  peek!: ChromaRepositoryInterface<TestDocument>['peek'];
  clear!: ChromaRepositoryInterface<TestDocument>['clear'];
  getCollectionInfo!: ChromaRepositoryInterface<TestDocument>['getCollectionInfo'];

  // Custom business logic methods
  async findByCategory(category: string): Promise<TestDocument[]> {
    return this.findAll();
  }

  async findHighPriority(): Promise<TestDocument[]> {
    return this.findAll();
  }

  async searchByTags(query: string, tags: string[]): Promise<TestDocument[]> {
    return this.search(query, {
      limit: 20,
    });
  }
}

/**
 * Example usage function to demonstrate functionality
 */
export async function demonstrateRepository(
  repository: TestDocumentRepository
): Promise<void> {
  // Create a test document
  const document: Omit<TestDocument, 'id'> = {
    content: 'This is a test document for the new repository system',
    metadata: {
      category: 'testing',
      priority: 9,
      tags: ['test', 'repository', 'chromadb'],
    },
  };

  try {
    // Test create operation
    const created = await repository.create(document);
    console.log('Created document:', created.id);

    // Test search operation
    const searchResults = await repository.search('test document');
    console.log('Search results:', searchResults.length);

    // Test custom method
    const highPriorityDocs = await repository.findHighPriority();
    console.log('High priority documents:', highPriorityDocs.length);

    // Test count operation
    const totalCount = await repository.count();
    console.log('Total documents:', totalCount);
  } catch (error) {
    console.error('Repository operation failed:', error);
  }
}
