/**
 * @fileoverview Comprehensive ChromaDB Decorator Usage Examples
 *
 * This file demonstrates real-world usage patterns for the ChromaDB decorator ecosystem,
 * showing how to build production-ready vector search applications with minimal boilerplate.
 */

import { Injectable } from '@nestjs/common';
import {
  VectorQuery,
  ChromaRepository,
  Cached,
  Profiled,
  Retry,
  VectorQueryParams,
  RepositorySearchOptions,
  RetryPresets,
  DecoratorPresets,
  BaseDocument,
  CollectionConfig,
} from '../decorators';
import { ChromaDBService } from '../services/chroma.service';

// =====================================================================
// Document Type Definitions
// =====================================================================

/**
 * User document interface with type-safe metadata
 */
interface UserDocument extends BaseDocument<{
  name: string;
  email: string;
  age: number;
  role: 'user' | 'admin' | 'moderator';
  interests: string[];
  joinedAt: string;
  lastActive?: string;
  subscription?: 'free' | 'premium' | 'enterprise';
}> {}

/**
 * Product document interface with rich metadata
 */
interface ProductDocument extends BaseDocument<{
  title: string;
  description: string;
  category: string;
  price: number;
  tags: string[];
  brand: string;
  availability: 'in_stock' | 'out_of_stock' | 'pre_order';
  rating: number;
  reviewCount: number;
}> {}

/**
 * Memory document for AI agents
 */
interface MemoryDocument extends BaseDocument<{
  agentId: string;
  sessionId: string;
  memoryType: 'conversation' | 'fact' | 'preference' | 'context';
  importance: number; // 1-10
  expiresAt?: string;
  tags: string[];
  relatedMemories?: string[];
}> {}

// =====================================================================
// Example 1: Basic Vector Search Service
// =====================================================================

@Injectable()
export class DocumentSearchService {
  constructor(private chromaService: ChromaDBService) {}

  /**
   * Basic vector search with auto-embedding and caching
   */
  @VectorQuery({
    collection: 'documents',
    autoEmbed: true,
    defaultLimit: 10,
    includeMetadata: true,
    includeDocuments: true,
    includeDistances: true,
    validateParams: true,
  })
  @Cached({
    ttl: 300000, // 5 minutes
    keyStrategy: 'collection_aware',
    enableStats: true,
  })
  @Profiled({
    slowQueryThreshold: 100,
    logLevel: 'slow',
    category: 'search',
  })
  async searchDocuments(params: VectorQueryParams) {
    // Implementation handled by decorators
    // This method body is replaced by @VectorQuery decorator
  }

  /**
   * Search with custom filters and retry logic
   */
  @VectorQuery({
    collection: 'documents',
    autoEmbed: true,
    defaultLimit: 20,
    similarityThreshold: 0.7,
  })
  @Retry(RetryPresets.vectorSearch)
  async searchWithFilters(
    query: string,
    category: string,
    minRating?: number
  ) {
    const filters: any = { category };
    if (minRating) {
      filters.rating = { $gte: minRating };
    }

    return this.searchDocuments({
      query,
      filters,
      limit: 20,
    });
  }

  /**
   * Similarity search using pre-computed embeddings
   */
  @VectorQuery({
    collection: 'documents',
    autoEmbed: false, // Using pre-computed embeddings
    includeDistances: true,
  })
  @Cached({ ttl: 600000 }) // 10 minutes
  async findSimilarByEmbedding(embedding: number[], limit = 5) {
    return this.searchDocuments({
      embedding,
      limit,
    });
  }
}

// =====================================================================
// Example 2: Repository Pattern with Full CRUD
// =====================================================================

@Injectable()
@ChromaRepository({
  collection: 'users',
  autoEmbed: true,
  enableCaching: true,
  enableValidation: true,
  autoTimestamp: true,
  autoGenerateIds: true,
  defaultBatchSize: 50,
})
export class UserRepository {
  constructor(private chromaService: ChromaDBService) {}

  // All CRUD methods are auto-generated by @ChromaRepository decorator:
  // - create(document, options?)
  // - createMany(documents, options?)
  // - findById(id, options?)
  // - findByIds(ids, options?)
  // - findAll(options?)
  // - update(id, updates, options?)
  // - updateMany(updates, options?)
  // - upsert(document, options?)
  // - upsertMany(documents, options?)
  // - delete(id, options?)
  // - deleteMany(ids, options?)
  // - deleteByFilter(where?, whereDocument?, options?)
  // - search(query, options?)
  // - searchWithScores(query, options?)
  // - searchSimilar(embedding, options?)
  // - count(where?, whereDocument?)
  // - exists(id)
  // - peek(limit?)
  // - clear()
  // - getCollectionInfo()

  /**
   * Custom business logic method - find user by email
   */
  @Cached({ ttl: 300000, keyStrategy: 'manual' })
  @Profiled({ category: 'user_lookup' })
  async findByEmail(email: string): Promise<UserDocument | null> {
    const users = await this.findAll({ where: { email } });
    return users[0] || null;
  }

  /**
   * Find users by role with advanced filtering
   */
  @VectorQuery({
    collection: 'users',
    autoEmbed: true,
    defaultLimit: 50,
  })
  @Cached({
    ttl: 180000, // 3 minutes
    keyGenerator: (role, interests) => `users_by_role:${role}:${interests?.join(',')}`,
  })
  async findByRoleAndInterests(
    role: 'user' | 'admin' | 'moderator',
    interests?: string[]
  ): Promise<UserDocument[]> {
    const filters: any = { role };
    if (interests && interests.length > 0) {
      filters.interests = { $in: interests };
    }

    return this.findAll({ where: filters });
  }

  /**
   * Semantic search for users based on description
   */
  @VectorQuery({
    collection: 'users',
    autoEmbed: true,
    includeDistances: true,
  })
  @Profiled({
    slowQueryThreshold: 200,
    includeParameters: true,
  })
  async searchUsers(
    query: string,
    options: RepositorySearchOptions = {}
  ): Promise<UserDocument[]> {
    return this.search(query, {
      limit: 20,
      threshold: 0.7,
      ...options,
    });
  }

  /**
   * Find premium users with cache warming
   */
  @Cached({
    ttl: 900000, // 15 minutes
    refreshStrategy: 'background',
    refreshThreshold: 0.8,
  })
  async findPremiumUsers(): Promise<UserDocument[]> {
    return this.findAll({
      where: {
        subscription: { $in: ['premium', 'enterprise'] },
      },
    });
  }
}

// =====================================================================
// Example 3: Product Search with Advanced Features
// =====================================================================

@Injectable()
export class ProductSearchService {
  constructor(
    private chromaService: ChromaDBService,
    private userRepository: UserRepository
  ) {}

  /**
   * Multi-collection search across products and reviews
   */
  @VectorQuery({
    collection: 'products',
    autoEmbed: true,
    defaultLimit: 15,
    includeDistances: true,
  })
  @Cached({
    ttl: 300000,
    collectionAware: true,
    refreshStrategy: 'background',
  })
  @Profiled({
    slowQueryThreshold: 150,
    enablePercentiles: true,
    category: 'product_search',
  })
  @Retry({
    maxAttempts: 3,
    strategy: 'exponential',
    retryableErrors: [/timeout/i, /connection/i],
  })
  async searchProducts(params: VectorQueryParams) {
    // Auto-implemented by decorator
  }

  /**
   * Personalized product recommendations
   */
  @VectorQuery({
    collection: 'products',
    autoEmbed: true,
    resultTransformer: (result) => {
      // Custom result transformation
      return result.documents[0]
        .filter((doc: any) => doc !== null)
        .map((doc: any, index: number) => ({
          product: doc,
          score: 1 - (result.distances[0][index] || 0),
          relevance: calculateRelevance(doc, result.distances[0][index]),
        }));
    },
  })
  @Cached({
    ttl: 600000, // 10 minutes for personalized results
    keyGenerator: (userId, preferences) =>
      `recommendations:${userId}:${JSON.stringify(preferences)}`,
  })
  async getPersonalizedRecommendations(
    userId: string,
    preferences: string[],
    limit = 10
  ) {
    // Get user profile for personalization
    const user = await this.userRepository.findById(userId);

    // Build search query based on preferences
    const query = preferences.join(' ');

    return this.searchProducts({
      query,
      limit,
      filters: {
        availability: 'in_stock',
        rating: { $gte: 3.5 },
      },
    });
  }

  /**
   * Category-specific search with performance optimization
   */
  @VectorQuery({
    collection: 'products',
    autoEmbed: true,
    defaultFilters: { availability: 'in_stock' },
  })
  @Cached({
    ttl: 240000, // 4 minutes
    keyStrategy: 'collection_aware',
    maxSize: 1000, // Limit cache size
  })
  @Profiled({
    samplingRate: 0.1, // Sample 10% of requests
    category: 'category_search',
  })
  async searchByCategory(
    query: string,
    category: string,
    priceRange?: { min?: number; max?: number }
  ) {
    const filters: any = { category };

    if (priceRange) {
      if (priceRange.min !== undefined) {
        filters.price = { $gte: priceRange.min };
      }
      if (priceRange.max !== undefined) {
        filters.price = { ...filters.price, $lte: priceRange.max };
      }
    }

    return this.searchProducts({
      query,
      filters,
      limit: 20,
    });
  }
}

// =====================================================================
// Example 4: AI Agent Memory System
// =====================================================================

@Injectable()
@ChromaRepository({
  collection: 'agent_memories',
  autoEmbed: true,
  enableCaching: false, // Real-time memory updates
  enableValidation: true,
  autoTimestamp: true,
  enableSoftDelete: true, // Keep memory history
})
export class AgentMemoryRepository {
  constructor(private chromaService: ChromaDBService) {}

  /**
   * Store new memory with automatic relationship detection
   */
  @Profiled({
    category: 'memory_storage',
    logLevel: 'all',
    includeMemoryMetrics: true,
  })
  @Retry({
    maxAttempts: 2,
    strategy: 'fixed',
    baseDelay: 100,
  })
  async storeMemory(
    agentId: string,
    sessionId: string,
    content: string,
    memoryType: MemoryDocument['metadata']['memoryType'],
    importance = 5
  ): Promise<MemoryDocument> {
    // Find related memories for context linking
    const relatedMemories = await this.findRelatedMemories(content, agentId);

    const memory = await this.create({
      content,
      metadata: {
        agentId,
        sessionId,
        memoryType,
        importance,
        tags: extractTags(content),
        relatedMemories: relatedMemories.map(m => m.id),
      },
    });

    return memory;
  }

  /**
   * Retrieve contextual memories for agent decision making
   */
  @VectorQuery({
    collection: 'agent_memories',
    autoEmbed: true,
    defaultLimit: 10,
    includeDistances: true,
  })
  @Cached({
    ttl: 30000, // 30 seconds for fresh context
    keyGenerator: (agentId, context) => `context:${agentId}:${hashContent(context)}`,
  })
  @Profiled({
    slowQueryThreshold: 50, // Memory retrieval should be fast
    category: 'memory_retrieval',
  })
  async getContextualMemories(
    agentId: string,
    currentContext: string,
    maxAge?: number
  ) {
    const filters: any = {
      agentId,
      importance: { $gte: 3 }, // Only important memories
    };

    if (maxAge) {
      const cutoffDate = new Date(Date.now() - maxAge).toISOString();
      filters.createdAt = { $gte: cutoffDate };
    }

    return this.search(currentContext, {
      where: filters,
      limit: 10,
      threshold: 0.6,
    });
  }

  /**
   * Find related memories using vector similarity
   */
  @VectorQuery({
    collection: 'agent_memories',
    autoEmbed: true,
    defaultLimit: 5,
  })
  private async findRelatedMemories(
    content: string,
    agentId: string
  ): Promise<MemoryDocument[]> {
    return this.search(content, {
      where: { agentId },
      limit: 5,
      threshold: 0.8, // High similarity threshold
    });
  }

  /**
   * Memory consolidation - merge similar memories
   */
  @Profiled({
    category: 'memory_consolidation',
    logLevel: 'all',
  })
  async consolidateMemories(agentId: string, sessionId: string): Promise<void> {
    // Find memories for consolidation
    const sessionMemories = await this.findAll({
      where: { agentId, sessionId },
    });

    // Group similar memories and create consolidated versions
    const groups = await this.groupSimilarMemories(sessionMemories);

    for (const group of groups) {
      if (group.length > 1) {
        const consolidated = await this.createConsolidatedMemory(group);

        // Mark original memories as consolidated
        await this.updateMany(
          group.map(memory => ({
            id: memory.id,
            data: {
              metadata: {
                ...memory.metadata,
                consolidated: true,
                consolidatedInto: consolidated.id,
              },
            },
          }))
        );
      }
    }
  }

  private async groupSimilarMemories(
    memories: MemoryDocument[]
  ): Promise<MemoryDocument[][]> {
    // Implementation would use vector similarity to group memories
    // This is a simplified version
    return memories.reduce((groups: MemoryDocument[][], memory) => {
      // Find similar group or create new one
      return groups;
    }, []);
  }

  private async createConsolidatedMemory(
    memories: MemoryDocument[]
  ): Promise<MemoryDocument> {
    const consolidatedContent = memories
      .map(m => m.content)
      .join('\n\n--- CONSOLIDATED ---\n\n');

    const avgImportance = Math.round(
      memories.reduce((sum, m) => sum + m.metadata.importance, 0) / memories.length
    );

    return this.create({
      content: consolidatedContent,
      metadata: {
        agentId: memories[0].metadata.agentId,
        sessionId: memories[0].metadata.sessionId,
        memoryType: 'context',
        importance: Math.min(10, avgImportance + 1), // Boost consolidated importance
        tags: [...new Set(memories.flatMap(m => m.metadata.tags))],
        relatedMemories: memories.map(m => m.id),
      },
    });
  }
}

// =====================================================================
// Example 5: Multi-Tenant SaaS Application
// =====================================================================

@Injectable()
export class TenantDocumentService {
  constructor(private chromaService: ChromaDBService) {}

  /**
   * Tenant-aware document search with isolation
   */
  @VectorQuery({
    collection: 'tenant_documents',
    autoEmbed: true,
    defaultLimit: 20,
    validateParams: true,
  })
  @Cached({
    ttl: 300000,
    keyGenerator: (tenantId, query, filters) =>
      `tenant:${tenantId}:search:${query}:${JSON.stringify(filters)}`,
    namespace: 'tenant_search',
  })
  @Profiled({
    category: 'tenant_search',
    tags: { service: 'document', feature: 'search' },
  })
  @Retry(RetryPresets.network)
  async searchTenantDocuments(
    tenantId: string,
    query: string,
    additionalFilters: any = {}
  ) {
    // Enforce tenant isolation at query level
    const filters = {
      tenantId, // Always include tenant ID
      ...additionalFilters,
    };

    return this.searchDocuments({
      query,
      filters,
      limit: 20,
    });
  }

  /**
   * Bulk operations with tenant validation
   */
  @Profiled({
    category: 'bulk_operations',
    includeParameters: false, // Don't log sensitive data
  })
  @Retry({
    maxAttempts: 2,
    strategy: 'linear',
    baseDelay: 1000,
  })
  async bulkCreateDocuments(
    tenantId: string,
    documents: Array<Omit<BaseDocument, 'id'>>
  ) {
    // Validate tenant access and add tenant metadata
    const tenantDocuments = documents.map(doc => ({
      ...doc,
      metadata: {
        ...doc.metadata,
        tenantId,
        createdAt: new Date().toISOString(),
      },
    }));

    // Use ChromaDB bulk operations
    return this.chromaService.addDocuments(
      'tenant_documents',
      tenantDocuments.map(doc => ({
        id: generateId(),
        content: doc.content,
        metadata: doc.metadata,
      })),
      { batchSize: 100 }
    );
  }

  // Placeholder method for @VectorQuery decorator
  private async searchDocuments(params: VectorQueryParams) {
    // Implementation replaced by decorator
  }
}

// =====================================================================
// Utility Functions
// =====================================================================

function calculateRelevance(product: any, distance: number): string {
  const similarity = 1 - distance;
  if (similarity > 0.9) return 'excellent';
  if (similarity > 0.7) return 'good';
  if (similarity > 0.5) return 'fair';
  return 'poor';
}

function extractTags(content: string): string[] {
  // Simple tag extraction - in reality would use NLP
  const words = content.toLowerCase().split(/\s+/);
  return words.filter(word => word.length > 3 && !commonWords.includes(word));
}

function hashContent(content: string): string {
  // Simple hash for demonstration
  return Buffer.from(content).toString('base64').substring(0, 16);
}

function generateId(): string {
  return `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
}

const commonWords = [
  'the', 'and', 'that', 'have', 'for', 'not', 'with', 'you', 'this', 'but',
  'his', 'from', 'they', 'she', 'her', 'been', 'than', 'its', 'would', 'there'
];

/**
 * Example usage summary:
 *
 * 1. **Basic Vector Search**: Simple search with auto-embedding and caching
 * 2. **Repository Pattern**: Full CRUD operations with minimal code
 * 3. **Advanced Search**: Multi-collection, personalized, category-specific
 * 4. **AI Memory System**: Real-time memory storage and retrieval for agents
 * 5. **Multi-Tenant SaaS**: Secure tenant isolation with bulk operations
 *
 * All examples demonstrate:
 * - Zero boilerplate code for common operations
 * - Type safety with IntelliSense support
 * - Production-ready error handling and retry logic
 * - Intelligent caching with collection-aware invalidation
 * - Comprehensive performance monitoring
 * - Decorator composition without conflicts
 */
