/**
 * @fileoverview Type-Safe Repository Example
 * 
 * This example demonstrates the enhanced type safety features of the @ChromaRepository
 * decorator, showcasing proper generic usage, type constraints, and error handling.
 */

import { Injectable, Logger } from '@nestjs/common';
import { BaseDocument } from '../../../types/document-types.interface';
import { ChromaDBService } from '../../../services/chromadb.service';
import { 
  ChromaRepository, 
  ChromaRepositoryConfig,
  RepositoryOperationOptions,
  RepositorySearchOptions 
} from '../chroma-repository.decorator';
import { 
  isValidBaseDocument,
  assertValidDocument,
  TypeSafeConverter,
  TypeSafeMethod 
} from '../repository-type-guards';

// =====================================================================
// 1. Define Strongly Typed Document Interfaces
// =====================================================================

/**
 * User document with strongly typed metadata
 */
interface UserDocument extends BaseDocument<{
  readonly name: string;
  readonly email: string;
  readonly age: number;
  readonly role: 'user' | 'admin' | 'moderator';
  readonly tags: readonly string[];
  readonly isActive: boolean;
  readonly joinedAt: string;
  readonly lastLoginAt?: string;
}> {}

/**
 * Product document with strongly typed metadata
 */
interface ProductDocument extends BaseDocument<{
  readonly title: string;
  readonly description: string;
  readonly price: number;
  readonly category: string;
  readonly inStock: boolean;
  readonly tags: readonly string[];
  readonly rating: number;
  readonly reviewCount: number;
}> {}

// =====================================================================
// 2. Type-Safe Repository Implementation
// =====================================================================

/**
 * Type-safe user repository with enhanced validation
 */
@Injectable()
@ChromaRepository<UserDocument>({
  collection: 'users',
  autoEmbed: true,
  enableCaching: true,
  enableValidation: true,
  autoTimestamp: true,
  autoGenerateIds: true,
  enableSoftDelete: false,
  errorHandling: 'throw',
})
export class UserRepository {
  private readonly logger = new Logger(UserRepository.name);

  constructor(
    private readonly chromaService: ChromaDBService
  ) {}

  // All CRUD methods are auto-generated by the decorator with full type safety

  /**
   * Custom method: Find users by email with type validation
   */
  @TypeSafeMethod<[string, RepositoryOperationOptions?], Promise<UserDocument | null>>(
    ([email, options]) => {
      if (typeof email !== 'string' || email.length === 0) {
        throw new Error('Email must be a non-empty string');
      }
    }
  )
  async findByEmail(email: string, options?: RepositoryOperationOptions): Promise<UserDocument | null> {
    const users = await this.findAll({ 
      where: { email },
      ...options 
    });

    const user = users[0] || null;
    
    // Type-safe validation
    if (user && !isValidBaseDocument<UserDocument>(user)) {
      this.logger.error('Retrieved user document failed type validation');
      return null;
    }

    return user;
  }

  /**
   * Custom method: Find adult users with type constraints
   */
  async findAdultUsers(minAge: number = 18): Promise<UserDocument[]> {
    // Input validation
    if (typeof minAge !== 'number' || minAge < 0 || minAge > 150) {
      throw new Error('Invalid age constraint');
    }

    const users = await this.findAll({
      where: { age: { $gte: minAge } }
    });

    // Type-safe conversion
    return TypeSafeConverter.toDocumentArray<UserDocument>(users, true);
  }

  /**
   * Custom method: Search users by role with type safety
   */
  async findUsersByRole(
    role: UserDocument['metadata']['role'],
    searchQuery?: string,
    options: RepositorySearchOptions = {}
  ): Promise<UserDocument[]> {
    // Validate role enum
    const validRoles: UserDocument['metadata']['role'][] = ['user', 'admin', 'moderator'];
    if (!validRoles.includes(role)) {
      throw new Error(`Invalid role: ${role}. Must be one of: ${validRoles.join(', ')}`);
    }

    if (searchQuery) {
      // Vector search with metadata filter
      return await this.search(searchQuery, {
        where: { role },
        limit: options.limit || 20,
        ...options
      });
    } else {
      // Metadata filter only
      return await this.findAll({
        where: { role },
        ...options
      });
    }
  }

  /**
   * Custom method: Create user with comprehensive validation
   */
  async createUserSafely(userData: {
    name: string;
    email: string;
    age: number;
    role: UserDocument['metadata']['role'];
    content?: string;
  }): Promise<UserDocument> {
    // Input validation
    if (!userData.name || userData.name.trim().length === 0) {
      throw new Error('Name is required');
    }

    if (!userData.email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(userData.email)) {
      throw new Error('Valid email is required');
    }

    if (typeof userData.age !== 'number' || userData.age < 0 || userData.age > 150) {
      throw new Error('Age must be between 0 and 150');
    }

    // Check if user already exists
    const existingUser = await this.findByEmail(userData.email);
    if (existingUser) {
      throw new Error(`User with email ${userData.email} already exists`);
    }

    // Create user document with type safety
    const userDocument: Omit<UserDocument, 'id'> = {
      content: userData.content || `User profile for ${userData.name}`,
      metadata: {
        name: userData.name,
        email: userData.email,
        age: userData.age,
        role: userData.role,
        tags: [],
        isActive: true,
        joinedAt: new Date().toISOString(),
      }
    };

    // Validate document structure before creation
    const tempDoc = { ...userDocument, id: 'temp' } as UserDocument;
    assertValidDocument<UserDocument>(tempDoc, 'user document');

    return await this.create(userDocument);
  }

  /**
   * Custom method: Bulk update users with type safety
   */
  async updateUsersLastLogin(userIds: string[]): Promise<void> {
    if (!Array.isArray(userIds) || userIds.length === 0) {
      throw new Error('User IDs array is required');
    }

    const updates = userIds.map(id => ({
      id,
      data: {
        metadata: {
          lastLoginAt: new Date().toISOString()
        }
      } as Partial<UserDocument>
    }));

    const result = await this.updateMany(updates);
    
    if (!result.success) {
      throw new Error(`Failed to update users: ${result.errors?.join(', ')}`);
    }

    this.logger.log(`Updated last login for ${result.documentsProcessed} users`);
  }
}

// =====================================================================
// 3. Product Repository with Different Type Constraints
// =====================================================================

@Injectable()
@ChromaRepository<ProductDocument>({
  collection: 'products',
  autoEmbed: true,
  enableCaching: true,
  enableValidation: true,
  autoTimestamp: true,
  defaultBatchSize: 50,
  errorHandling: 'log_and_continue',
})
export class ProductRepository {
  private readonly logger = new Logger(ProductRepository.name);

  constructor(
    private readonly chromaService: ChromaDBService
  ) {}

  /**
   * Find products by category with price filtering
   */
  async findProductsByCategory(
    category: string,
    priceRange?: { min?: number; max?: number }
  ): Promise<ProductDocument[]> {
    const whereClause: Record<string, unknown> = { category };

    if (priceRange) {
      if (priceRange.min !== undefined) {
        whereClause.price = { ...whereClause.price as object, $gte: priceRange.min };
      }
      if (priceRange.max !== undefined) {
        whereClause.price = { ...whereClause.price as object, $lte: priceRange.max };
      }
    }

    return await this.findAll({ where: whereClause });
  }

  /**
   * Search products with semantic similarity and metadata filters
   */
  async searchProducts(query: string, filters: {
    category?: string;
    inStock?: boolean;
    minRating?: number;
    maxPrice?: number;
  } = {}): Promise<Array<{ product: ProductDocument; score: number }>> {
    const whereClause: Record<string, unknown> = {};

    if (filters.category) {
      whereClause.category = filters.category;
    }

    if (typeof filters.inStock === 'boolean') {
      whereClause.inStock = filters.inStock;
    }

    if (typeof filters.minRating === 'number') {
      whereClause.rating = { $gte: filters.minRating };
    }

    if (typeof filters.maxPrice === 'number') {
      whereClause.price = { 
        ...whereClause.price as object, 
        $lte: filters.maxPrice 
      };
    }

    return await this.searchWithScores(query, {
      where: whereClause,
      limit: 20,
      include: {
        metadata: true,
        documents: true,
        distances: true,
      }
    });
  }
}

// =====================================================================
// 4. Service Layer Using Type-Safe Repositories
// =====================================================================

@Injectable()
export class UserManagementService {
  constructor(
    private readonly userRepository: UserRepository,
    private readonly logger: Logger
  ) {}

  /**
   * Register new user with comprehensive validation
   */
  async registerUser(registrationData: {
    name: string;
    email: string;
    age: number;
  }): Promise<UserDocument> {
    try {
      return await this.userRepository.createUserSafely({
        ...registrationData,
        role: 'user',
        content: `Welcome ${registrationData.name}! Your profile is ready.`,
      });
    } catch (error) {
      this.logger.error('User registration failed', error);
      throw new Error(`Registration failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  /**
   * Find users with advanced search capabilities
   */
  async searchUsers(query: string, filters: {
    role?: UserDocument['metadata']['role'];
    minAge?: number;
    isActive?: boolean;
  } = {}): Promise<UserDocument[]> {
    let users: UserDocument[] = [];

    if (filters.role) {
      users = await this.userRepository.findUsersByRole(filters.role, query);
    } else {
      users = await this.userRepository.search(query, { limit: 50 });
    }

    // Apply additional filters
    if (filters.minAge !== undefined || filters.isActive !== undefined) {
      users = users.filter(user => {
        if (filters.minAge !== undefined && user.metadata.age < filters.minAge) {
          return false;
        }
        if (filters.isActive !== undefined && user.metadata.isActive !== filters.isActive) {
          return false;
        }
        return true;
      });
    }

    return users;
  }

  /**
   * Get user statistics with type safety
   */
  async getUserStatistics(): Promise<{
    total: number;
    byRole: Record<UserDocument['metadata']['role'], number>;
    averageAge: number;
    activeUsers: number;
  }> {
    const allUsers = await this.userRepository.findAll();

    const stats = {
      total: allUsers.length,
      byRole: {
        user: 0,
        admin: 0,
        moderator: 0,
      } as Record<UserDocument['metadata']['role'], number>,
      averageAge: 0,
      activeUsers: 0,
    };

    let totalAge = 0;

    for (const user of allUsers) {
      // Type-safe access to metadata
      stats.byRole[user.metadata.role]++;
      totalAge += user.metadata.age;
      
      if (user.metadata.isActive) {
        stats.activeUsers++;
      }
    }

    stats.averageAge = allUsers.length > 0 ? totalAge / allUsers.length : 0;

    return stats;
  }
}

// =====================================================================
// 5. Example Usage and Testing
// =====================================================================

/**
 * Example usage demonstrating type safety features
 */
export class TypeSafeRepositoryExample {
  constructor(
    private readonly userRepository: UserRepository,
    private readonly productRepository: ProductRepository,
    private readonly userManagementService: UserManagementService
  ) {}

  async demonstrateTypeSafety(): Promise<void> {
    console.log('=== Type-Safe Repository Example ===');

    try {
      // 1. Create user with type validation
      const newUser = await this.userRepository.createUserSafely({
        name: 'John Doe',
        email: 'john.doe@example.com',
        age: 30,
        role: 'user',
      });

      console.log('✅ Created user:', newUser.id);

      // 2. Type-safe search
      const adminUsers = await this.userRepository.findUsersByRole('admin', 'experienced');
      console.log(`✅ Found ${adminUsers.length} admin users`);

      // 3. Semantic search with metadata filters
      const products = await this.productRepository.searchProducts('laptop computer', {
        category: 'electronics',
        inStock: true,
        minRating: 4.0,
        maxPrice: 1500,
      });

      console.log(`✅ Found ${products.length} matching products`);

      // 4. Service layer usage
      const userStats = await this.userManagementService.getUserStatistics();
      console.log('✅ User statistics:', userStats);

      // 5. Demonstrate type safety - this would fail at compile time:
      // await this.userRepository.findUsersByRole('invalid_role'); // ❌ TypeScript error

      console.log('✅ All type safety demonstrations completed successfully');

    } catch (error) {
      console.error('❌ Error in type safety demonstration:', error);
      throw error;
    }
  }
}

/**
 * Type safety validation example
 */
export function demonstrateTypeValidation(): void {
  // ✅ Valid document
  const validUser: UserDocument = {
    id: 'user-123',
    content: 'User profile content',
    metadata: {
      name: 'Jane Doe',
      email: 'jane@example.com',
      age: 25,
      role: 'user',
      tags: ['developer', 'typescript'],
      isActive: true,
      joinedAt: '2024-01-01T00:00:00Z',
    }
  };

  console.log('Valid user document:', isValidBaseDocument<UserDocument>(validUser));

  // ❌ Invalid document (missing required fields)
  const invalidDocument = {
    id: 'invalid-123',
    // missing content
    metadata: {
      name: 'Invalid User',
      // missing email and other required fields
    }
  };

  console.log('Invalid document:', isValidBaseDocument<UserDocument>(invalidDocument));

  // ✅ Safe conversion
  const safeUser = TypeSafeConverter.toDocument<UserDocument>(validUser);
  console.log('Safe conversion result:', safeUser?.id);

  const unsafeUser = TypeSafeConverter.toDocument<UserDocument>(invalidDocument);
  console.log('Unsafe conversion result:', unsafeUser); // Should be null
}