import {
  CreatedAt,
  Id,
  JsonProperty,
  Neo4jBaseEntity,
  Neo4jEntity,
  Neo4jProp,
  NodeKey,
  NotNull,
  PropIndex,
  Unique,
  UpdatedAt,
} from '@hive-academy/nestjs-neo4j';

/**
 * Thread Entity
 *
 * Purpose: Thread metadata storage for memory isolation across checkpoints
 * Current Usage: Neo4jThreadRegistryAdapter (thread-registry pattern)
 *
 * Represents conversation threads in the LangGraph memory system with
 * comprehensive metadata tracking, user isolation, and timestamp management.
 *
 * **Architecture Pattern**: Neo4j Entity with Repository Token Support
 * **Reference**: ApprovalRequest (approval-request.entity.ts:26-127)
 *
 * **Storage Independence**:
 * - This entity stores thread metadata only
 * - Checkpoint storage (conversation history) is handled separately by BaseStore
 * - Thread registry answers "what conversations exist?" not "what was said?"
 *
 * **Use Cases**:
 * - List user conversations in sidebar
 * - Track last activity per thread
 * - Manage thread lifecycle (create, update, delete)
 * - Enable memory isolation (each thread has independent checkpoint namespace)
 */
@Neo4jEntity('Thread', {
  description: 'Conversation thread metadata for memory isolation',
})
@NodeKey(['userId', 'threadId'])
export class Thread extends Neo4jBaseEntity {
  /**
   * Unique thread identifier
   * Format: thread-{timestamp}-{random}
   * Generated by adapter on creation
   */
  @Id()
  @Unique()
  threadId!: string;

  /**
   * User identifier who owns this thread
   * Used for user isolation and access control
   */
  @Neo4jProp()
  @NotNull()
  @PropIndex()
  userId!: string;

  /**
   * When the thread was created
   * Indexed for sorting by creation time
   */
  @PropIndex({ type: 'RANGE' })
  @CreatedAt()
  createdAt!: Date;

  /**
   * When the last message was sent in this thread
   * Primary field for "most recent conversations" sorting
   * Updated on every message
   */
  @Neo4jProp()
  @NotNull()
  @PropIndex({ type: 'RANGE' })
  lastMessageAt!: Date;

  /**
   * Optional human-readable thread title
   * Can be auto-generated from first message or user-provided
   */
  @Neo4jProp()
  title?: string;

  /**
   * Additional thread metadata as JSON object
   * Stores arbitrary data like: source, tags, status, etc.
   *
   * Example:
   * {
   *   source: 'web_ui',
   *   tags: ['research', 'important'],
   *   status: 'active',
   *   customField: 'value'
   * }
   */
  @Neo4jProp()
  @JsonProperty()
  metadata?: Record<string, unknown>;

  /**
   * Auto-managed update timestamp
   * Updated automatically on any entity modification
   */
  @UpdatedAt()
  updatedAt!: Date;
}
