/**
 * Base Repository Interface
 * This interface defines the CRUD methods that are auto-generated by the @Repository decorator
 */
import type { FindOptions } from './crud-operations';
import type { BaseEntity } from '../types/neo4j-types';

/**
 * Base repository interface that provides type safety for auto-generated CRUD methods
 */
export interface IBaseRepository<TEntity extends BaseEntity> {
  /**
   * Find a single entity by ID
   * Auto-generated by @Repository decorator
   */
  findById(id: string): Promise<TEntity | null>;

  /**
   * Find multiple entities with optional filtering and pagination
   * Auto-generated by @Repository decorator
   */
  findAll(options?: FindOptions<TEntity>): Promise<TEntity[]>;

  /**
   * Create a new entity
   * Auto-generated by @Repository decorator
   */
  create(data: Partial<TEntity>): Promise<TEntity>;

  /**
   * Update an existing entity
   * Auto-generated by @Repository decorator
   */
  update(id: string, updates: Partial<TEntity>): Promise<TEntity | null>;

  /**
   * Delete an entity by ID
   * Auto-generated by @Repository decorator
   */
  delete(id: string): Promise<boolean>;

  /**
   * Count entities with optional filtering
   * Auto-generated by @Repository decorator
   */
  count(where?: Record<string, any>): Promise<number>;

  /**
   * Check if an entity exists by ID
   * Auto-generated by @Repository decorator
   */
  exists(id: string): Promise<boolean>;
}

/**
 * Abstract base repository class that implements IBaseRepository
 * Services can extend this class to get proper TypeScript support for auto-generated methods
 */
export abstract class BaseRepositoryService<TEntity extends BaseEntity>
  implements IBaseRepository<TEntity>
{
  // These methods are implemented by the @Repository decorator at runtime
  // TypeScript needs these declarations for proper type checking

  async findById(id: string): Promise<TEntity | null> {
    throw new Error('Method implemented by @Repository decorator');
  }

  async findAll(options?: FindOptions<TEntity>): Promise<TEntity[]> {
    throw new Error('Method implemented by @Repository decorator');
  }

  async create(data: Partial<TEntity>): Promise<TEntity> {
    throw new Error('Method implemented by @Repository decorator');
  }

  async update(id: string, updates: Partial<TEntity>): Promise<TEntity | null> {
    throw new Error('Method implemented by @Repository decorator');
  }

  async delete(id: string): Promise<boolean> {
    throw new Error('Method implemented by @Repository decorator');
  }

  async count(where?: Record<string, any>): Promise<number> {
    throw new Error('Method implemented by @Repository decorator');
  }

  async exists(id: string): Promise<boolean> {
    throw new Error('Method implemented by @Repository decorator');
  }

  /**
   * Protected method to get the Neo4j service instance
   * This is provided by the @Repository decorator's enhanced constructor
   */
  protected getNeo4jService(): any {
    return (this as any).neo4jService;
  }
}