/* eslint-disable @typescript-eslint/no-unsafe-function-type */
import 'reflect-metadata';
import { SetMetadata, Injectable } from '@nestjs/common';
import {
  DECORATOR_METADATA_KEYS,
  type RepositoryConfig,
  type QueryExecutionOptions,
} from '../interfaces/decorator-metadata.interface';
import {
  findOne,
  findMany,
  create,
  update,
  deleteEntity,
  count,
  exists,
  getEntityLabel as getCrudEntityLabel,
  type FindOptions,
  type DeleteOptions,
  type NeogmaModelInterface,
} from './crud-operations';
import type { NeogmaModel, NeogmaEntity } from '../types/neogma-types';
import type { NeogmaService } from '../core/neogma.service';

/**
 * Configuration for the @Neo4jRepository decorator with enterprise-grade type safety
 */
export interface Neo4jRepositoryConfig<
  TEntity extends NeogmaEntity = NeogmaEntity
> {
  /** Entity type this repository manages - properly typed for type safety */
  entityType: () => new () => TEntity;
  /** Neo4j label for the entity */
  label?: string;
  /** Custom connection name */
  connectionName?: string;
  /** Default query options for all operations */
  defaultOptions?: QueryExecutionOptions;
  /** Description for documentation */
  description?: string;
  /** Tags for categorization */
  tags?: string[];
  /** Whether to auto-generate CRUD methods */
  autoGenerate?: boolean;
}

/**
 *  @Neo4jRepository decorator for repository pattern implementation
 *
 * Features:
 * - Auto-generation of basic CRUD operations
 * - Type-safe entity management
 * - Connection management
 * - Default query options inheritance
 * - Automatic dependency injection setup
 *
 * @example
 * ```typescript
 * @Neo4jRepository({
 *   entityType: () => User,
 *   label: 'User',
 *   autoGenerate: true,
 *   defaultOptions: {
 *     cache: { enabled: true, ttl: 300000 }
 *   }
 * })
 * export class UserRepository {
 *   // Auto-generated methods:
 *   // - findById(id: string): Promise<User | null>
 *   // - findAll(options?: FindOptions): Promise<User[]>
 *   // - create(data: Partial<User>): Promise<User>
 *   // - update(id: string, updates: Partial<User>): Promise<User>
 *   // - delete(id: string): Promise<boolean>
 *
 *   @CypherQuery<User[]>({ ... })
 *   async findByEmail(email: string): Promise<User[]> {
 *     // Custom query method
 *   }
 * }
 * ```
 */
export function Neo4jRepository<TEntity extends NeogmaEntity = NeogmaEntity>(
  config?: Neo4jRepositoryConfig<TEntity>
): ClassDecorator {
  return (constructor: Function) => {
    // Default configuration if none provided
    const finalConfig: Neo4jRepositoryConfig<TEntity> = config || {
      entityType: () => Object as unknown as new () => TEntity,
    };

    // Validate configuration
    validateRepositoryConfig(
      finalConfig as Neo4jRepositoryConfig<NeogmaEntity>
    );

    // Extract entity information
    const entityType = finalConfig.entityType;
    const label = finalConfig.label || getCrudEntityLabel(entityType as any);

    // Create repository metadata
    const metadata: RepositoryConfig = {
      id: `Repository:${constructor.name}`,
      entityType: finalConfig.entityType,
      label,
      connectionName: finalConfig.connectionName,
      defaultOptions: finalConfig.defaultOptions,
      description:
        finalConfig.description || `Repository for ${label} entities`,
      tags: finalConfig.tags || ['repository', label.toLowerCase()],
      enabled: true,
    };

    // Use direct Reflect.defineMetadata for better compatibility
    // This ensures metadata survives when other decorators create newConstructor
    Reflect.defineMetadata(
      DECORATOR_METADATA_KEYS.REPOSITORY,
      metadata,
      constructor
    );

    // Also use SetMetadata for NestJS compatibility (belt and suspenders approach)
    SetMetadata(DECORATOR_METADATA_KEYS.REPOSITORY, metadata)(constructor);

    // Apply @Injectable decorator for dependency injection
    Injectable()(constructor);

    // Auto-generate CRUD methods if requested
    if (finalConfig.autoGenerate !== false) {
      addAutoGeneratedMethods(constructor, metadata);
    }

    // Enhance constructor to inject NeogmaService and model with proper generics
    const newConstructor = class extends (constructor as new (
      ...args: any[]
    ) => any) {
      protected neogmaService: NeogmaService;
      protected neogmaModel: NeogmaModel<TEntity>;
      protected entityLabel: string = label;
      protected defaultOptions: QueryExecutionOptions =
        finalConfig.defaultOptions || {};

      constructor(...args: any[]) {
        super(...args);

        // Find and inject NeogmaService from arguments
        this.neogmaService = this.findNeogmaService(args);

        if (!this.neogmaService) {
          throw new Error(
            `NeogmaService not found in ${constructor.name}. ` +
              'Ensure NeogmaService is injected in the constructor.'
          );
        }

        // For now, we'll need to get the model from the entity type
        // This requires the entity to define a static getModel() method
        this.neogmaModel = this.getModelFromEntityType(
          entityType
        ) as unknown as NeogmaModel<TEntity>;
      }

      /**
       * Find NeogmaService instance from constructor arguments
       */
      private findNeogmaService(args: any[]): NeogmaService {
        return args.find(
          (arg) =>
            arg && arg.constructor && arg.constructor.name === 'NeogmaService'
        );
      }

      /**
       * Get the NeogmaService instance
       */
      protected getNeogmaService(): NeogmaService {
        return this.neogmaService;
      }

      /**
       * Get the Neogma model for this entity
       */
      protected getNeogmaModel(): NeogmaModel<TEntity> {
        return this.neogmaModel;
      }

      /**
       * Get model from entity type - requires entity to have static getModel method
       */
      private getModelFromEntityType(
        entityType: () => new () => TEntity
      ): NeogmaModelInterface {
        try {
          const entity = entityType();

          // Try to get model from static method
          if (entity && typeof (entity as any).getModel === 'function') {
            return (entity as any).getModel();
          }

          // Fallback: create a mock model interface
          return this.createMockModel(label);
        } catch (error) {
          return this.createMockModel(label);
        }
      }

      /**
       * Create a model interface that uses NeogmaService's pure model operations
       */
      private createMockModel(labelName: string): NeogmaModelInterface {
        const service = this.neogmaService;

        return {
          async findOne(options: {
            where: Partial<NeogmaEntity>;
          }): Promise<{ toJson(): Record<string, unknown> } | null> {
            // Use model operations when available, fallback to service
            try {
              const model = service.getModel(labelName);
              const instance = await model.findOne(options);
              return instance;
            } catch {
              const id = options.where.id;
              if (typeof id === 'string') {
                const result = await service.findById(labelName, id);
                return result ? { toJson: () => result } : null;
              }
              return null;
            }
          },

          async findMany(options?: {
            where?: Partial<NeogmaEntity>;
            limit?: number;
            skip?: number;
            orderBy?: Array<{ [x: string]: 'ASC' | 'DESC' | undefined }>;
          }): Promise<Array<{ toJson(): Record<string, unknown> }>> {
            const findOptions = {
              where: options?.where,
              limit: options?.limit,
              skip: options?.skip,
              orderBy: options?.orderBy,
            };
            const results = await service.findMany(labelName, findOptions);
            return results.map((result) => ({ toJson: () => result }));
          },

          async create(
            data: Omit<NeogmaEntity, 'id' | 'createdAt' | 'updatedAt'>
          ): Promise<{ toJson(): Record<string, unknown> }> {
            const result = await service.create(labelName, data as any);
            return { toJson: () => result };
          },

          async update(
            data: Partial<Omit<NeogmaEntity, 'id' | 'createdAt'>>,
            options: { where: Partial<NeogmaEntity> }
          ): Promise<{ toJson(): Record<string, unknown> } | null> {
            const id = options.where.id;
            if (typeof id === 'string') {
              const result = await service.update(labelName, id, data as any);
              return result ? { toJson: () => result } : null;
            }
            return null;
          },

          async delete(options: {
            where: Partial<NeogmaEntity>;
            detach?: boolean;
          }): Promise<number> {
            const id = options.where.id;
            if (typeof id === 'string') {
              const success = await service.delete(
                labelName,
                id,
                options.detach
              );
              return success ? 1 : 0;
            }
            return 0;
          },

          async count(options?: {
            where?: Partial<NeogmaEntity>;
          }): Promise<number> {
            return await service.count(labelName, options?.where as any);
          },

          getLabel(): string {
            return labelName;
          },
        };
      }
    };

    // Preserve original class name and metadata
    Object.defineProperty(newConstructor, 'name', {
      value: constructor.name,
    });

    return newConstructor as any;
  };
}

/**
 * Simplified @Repository decorator
 */
export function Repository(entityType: () => any): ClassDecorator {
  return Neo4jRepository({
    entityType,
    autoGenerate: true,
  });
}

/**
 * Add auto-generated CRUD methods to the repository class
 * Uses the internal CRUD operation helpers for consistency
 */
function addAutoGeneratedMethods(
  constructor: any,
  metadata: RepositoryConfig
): void {
  const prototype = constructor.prototype;

  // Auto-generate findById method using new CRUD operations
  if (!prototype.findById) {
    prototype.findById = async function (id: string): Promise<any> {
      const model = this.getNeogmaModel();
      return await findOne(model, id);
    };
  }

  // Auto-generate findAll method using new CRUD operations
  if (!prototype.findAll) {
    prototype.findAll = async function (options?: FindOptions): Promise<any[]> {
      const model = this.getNeogmaModel();
      return await findMany(model, options);
    };
  }

  // Auto-generate create method using new CRUD operations
  if (!prototype.create) {
    prototype.create = async function (
      data: Record<string, any>
    ): Promise<any> {
      const model = this.getNeogmaModel();
      return await create(model, data);
    };
  }

  // Auto-generate update method using new CRUD operations
  if (!prototype.update) {
    prototype.update = async function (
      id: string,
      updates: Record<string, any>
    ): Promise<any> {
      const model = this.getNeogmaModel();
      return await update(model, id, updates);
    };
  }

  // Auto-generate delete method using new CRUD operations
  if (!prototype.delete) {
    prototype.delete = async function (
      id: string,
      options?: DeleteOptions
    ): Promise<boolean> {
      const model = this.getNeogmaModel();
      return await deleteEntity(model, id, options);
    };
  }

  // Auto-generate count method using new CRUD operations
  if (!prototype.count) {
    prototype.count = async function (
      where?: Record<string, any>
    ): Promise<number> {
      const model = this.getNeogmaModel();
      return await count(model, where);
    };
  }

  // Auto-generate exists method using new CRUD operations
  if (!prototype.exists) {
    prototype.exists = async function (id: string): Promise<boolean> {
      const model = this.getNeogmaModel();
      return await exists(model, id);
    };
  }
}

// FindOptions interface is now imported from crud-operations
// This ensures consistency between standalone usage and repository pattern

/**
 * Validate repository configuration
 */
function validateRepositoryConfig(config: Neo4jRepositoryConfig): void {
  if (!config.entityType || typeof config.entityType !== 'function') {
    throw new Error(
      'Neo4jRepository decorator requires a valid entityType function'
    );
  }

  try {
    config.entityType();
  } catch (error) {
    throw new Error('Neo4jRepository entityType function must be callable');
  }
}

// Use getEntityLabel from crud-operations for consistency
// Entity label extraction is now centralized in crud-operations module
