import 'reflect-metadata';
import { SetMetadata, Injectable } from '@nestjs/common';
import {
  DECORATOR_METADATA_KEYS,
  type RepositoryConfig,
  type QueryExecutionOptions,
} from '../interfaces/decorator-metadata.interface';
import {
  generateFindOneQuery,
  generateFindManyQuery,
  generateCreateQuery,
  generateUpdateQuery,
  generateDeleteQuery,
  generateCountQuery,
  generateExistsQuery,
  getEntityLabel as getCrudEntityLabel,
  type FindOptions,
  type DeleteOptions,
} from './crud-operations';

/**
 * Configuration for the @Neo4jRepository decorator
 */
export interface Neo4jRepositoryConfig {
  /** Entity type this repository manages */
  entityType: () => any;
  /** Neo4j label for the entity */
  label?: string;
  /** Custom connection name */
  connectionName?: string;
  /** Default query options for all operations */
  defaultOptions?: QueryExecutionOptions;
  /** Description for documentation */
  description?: string;
  /** Tags for categorization */
  tags?: string[];
  /** Whether to auto-generate CRUD methods */
  autoGenerate?: boolean;
}

/**
 *  @Neo4jRepository decorator for repository pattern implementation
 *
 * Features:
 * - Auto-generation of basic CRUD operations
 * - Type-safe entity management
 * - Connection management
 * - Default query options inheritance
 * - Automatic dependency injection setup
 *
 * @example
 * ```typescript
 * @Neo4jRepository({
 *   entityType: () => User,
 *   label: 'User',
 *   autoGenerate: true,
 *   defaultOptions: {
 *     cache: { enabled: true, ttl: 300000 }
 *   }
 * })
 * export class UserRepository {
 *   // Auto-generated methods:
 *   // - findById(id: string): Promise<User | null>
 *   // - findAll(options?: FindOptions): Promise<User[]>
 *   // - create(data: Partial<User>): Promise<User>
 *   // - update(id: string, updates: Partial<User>): Promise<User>
 *   // - delete(id: string): Promise<boolean>
 *
 *   @CypherQuery<User[]>({ ... })
 *   async findByEmail(email: string): Promise<User[]> {
 *     // Custom query method
 *   }
 * }
 * ```
 */
export function Neo4jRepository(
  config?: Neo4jRepositoryConfig
): ClassDecorator {
  return (constructor: any) => {
    // Default configuration if none provided
    const finalConfig = config || { entityType: () => Object };

    // Validate configuration
    validateRepositoryConfig(finalConfig);

    // Extract entity information
    const entityType = finalConfig.entityType();
    const label = finalConfig.label || getCrudEntityLabel(entityType);

    // Create repository metadata
    const metadata: RepositoryConfig = {
      id: `Repository:${constructor.name}`,
      entityType: finalConfig.entityType,
      label,
      connectionName: finalConfig.connectionName,
      defaultOptions: finalConfig.defaultOptions,
      description:
        finalConfig.description || `Repository for ${label} entities`,
      tags: finalConfig.tags || ['repository', label.toLowerCase()],
      enabled: true,
    };

    // Use direct Reflect.defineMetadata for better compatibility
    // This ensures metadata survives when other decorators create newConstructor
    Reflect.defineMetadata(
      DECORATOR_METADATA_KEYS.REPOSITORY,
      metadata,
      constructor
    );

    // Also use SetMetadata for NestJS compatibility (belt and suspenders approach)
    SetMetadata(DECORATOR_METADATA_KEYS.REPOSITORY, metadata)(constructor);

    // Apply @Injectable decorator for dependency injection
    Injectable()(constructor);

    // Auto-generate CRUD methods if requested
    if (finalConfig.autoGenerate !== false) {
      addAutoGeneratedMethods(constructor, metadata);
    }

    // Enhance constructor to inject Neo4j service
    const newConstructor = class extends constructor {
      protected neo4jService: any;
      protected entityLabel: string = label;
      protected defaultOptions: QueryExecutionOptions =
        finalConfig.defaultOptions || {};

      constructor(...args: any[]) {
        super(...args);

        // Find and inject Neo4j service from arguments
        this.neo4jService = this.findNeo4jService(args);

        if (!this.neo4jService) {
          throw new Error(
            `Neo4j service not found in ${constructor.name}. ` +
              'Ensure Neo4jService or Neo4jService is injected in the constructor.'
          );
        }
      }

      /**
       * Find Neo4j service instance from constructor arguments
       */
      private findNeo4jService(args: any[]): any {
        return args.find(
          (arg) =>
            arg &&
            (typeof arg.run === 'function' || typeof arg.run === 'function')
        );
      }

      /**
       * Get the Neo4j service instance
       */
      protected getNeo4jService(): any {
        return this.neo4jService;
      }

      /**
       * Execute query with repository defaults
       */
      protected async executeQuery<T>(
        query: string,
        params?: Record<string, any>,
        options?: QueryExecutionOptions
      ): Promise<T> {
        const mergedOptions = { ...this.defaultOptions, ...options };

        if (typeof this.neo4jService.run === 'function') {
          const result = await this.neo4jService.run(
            query,
            params,
            mergedOptions
          );
          return result.records;
        } else {
          const result = await this.neo4jService.run(
            query,
            params,
            mergedOptions
          );
          return result.records || result;
        }
      }
    };

    // Preserve original class name and metadata
    Object.defineProperty(newConstructor, 'name', {
      value: constructor.name,
    });

    return newConstructor as any;
  };
}

/**
 * Simplified @Repository decorator
 */
export function Repository(entityType: () => any): ClassDecorator {
  return Neo4jRepository({
    entityType,
    autoGenerate: true,
  });
}

/**
 * Add auto-generated CRUD methods to the repository class
 * Uses the internal CRUD operation helpers for consistency
 */
function addAutoGeneratedMethods(
  constructor: any,
  metadata: RepositoryConfig
): void {
  const prototype = constructor.prototype;
  const entityType = metadata.entityType;

  // Auto-generate findById method using helper
  if (!prototype.findById) {
    prototype.findById = async function (id: string): Promise<any> {
      const queryResult = generateFindOneQuery(entityType, id);
      const result = await this.executeQuery(
        queryResult.query,
        queryResult.params,
        { accessMode: 'READ' }
      );
      return result.length > 0 ? result[0].get('n') : null;
    };
  }

  // Auto-generate findAll method using helper
  if (!prototype.findAll) {
    prototype.findAll = async function (
      options?: FindOptions
    ): Promise<any[]> {
      const queryResult = generateFindManyQuery(entityType, options);
      const result = await this.executeQuery(
        queryResult.query,
        queryResult.params,
        { accessMode: 'READ' }
      );
      return result.map((record: any) => record.get('n'));
    };
  }

  // Auto-generate create method using helper
  if (!prototype.create) {
    prototype.create = async function (
      data: Record<string, any>
    ): Promise<any> {
      const queryResult = generateCreateQuery(entityType, data);
      const result = await this.executeQuery(
        queryResult.query,
        queryResult.params,
        { accessMode: 'WRITE' }
      );
      return result[0]?.get('n');
    };
  }

  // Auto-generate update method using helper
  if (!prototype.update) {
    prototype.update = async function (
      id: string,
      updates: Record<string, any>
    ): Promise<any> {
      const queryResult = generateUpdateQuery(entityType, id, updates);
      const result = await this.executeQuery(
        queryResult.query,
        queryResult.params,
        { accessMode: 'WRITE' }
      );
      return result.length > 0 ? result[0].get('n') : null;
    };
  }

  // Auto-generate delete method using helper
  if (!prototype.delete) {
    prototype.delete = async function (
      id: string,
      options?: DeleteOptions
    ): Promise<boolean> {
      const queryResult = generateDeleteQuery(entityType, id, options);
      const result = await this.executeQuery(
        queryResult.query,
        queryResult.params,
        { accessMode: 'WRITE' }
      );
      return result[0]?.get('deleted') || false;
    };
  }

  // Auto-generate count method using helper
  if (!prototype.count) {
    prototype.count = async function (
      where?: Record<string, any>
    ): Promise<number> {
      const queryResult = generateCountQuery(entityType, where);
      const result = await this.executeQuery(
        queryResult.query,
        queryResult.params,
        { accessMode: 'READ' }
      );
      return result[0]?.get('count') || 0;
    };
  }

  // Auto-generate exists method using helper
  if (!prototype.exists) {
    prototype.exists = async function (id: string): Promise<boolean> {
      const queryResult = generateExistsQuery(entityType, id);
      const result = await this.executeQuery(
        queryResult.query,
        queryResult.params,
        { accessMode: 'READ' }
      );
      return result[0]?.get('exists') || false;
    };
  }
}

// FindOptions interface is now imported from crud-operations
// This ensures consistency between standalone usage and repository pattern

/**
 * Validate repository configuration
 */
function validateRepositoryConfig(config: Neo4jRepositoryConfig): void {
  if (!config.entityType || typeof config.entityType !== 'function') {
    throw new Error(
      'Neo4jRepository decorator requires a valid entityType function'
    );
  }

  try {
    config.entityType();
  } catch (error) {
    throw new Error('Neo4jRepository entityType function must be callable');
  }
}

// Use getEntityLabel from crud-operations for consistency
// Entity label extraction is now centralized in crud-operations module
