import { z } from 'zod';

// =============================================================================
// StreamEventType Enumeration
// =============================================================================

/**
 * Comprehensive set of event types emitted by the LangGraph streaming backend.
 *
 * @remarks
 * - Total of 20 event types across 8 categories
 * - Used for type discrimination in `StreamUpdate` discriminated union
 * - Backend emits these events via SSE during workflow execution
 *
 * @public
 */
export enum StreamEventType {
  // Workflow lifecycle events
  /** Emitted when workflow execution begins */
  WORKFLOW_START = 'workflow:start',
  /** Emitted when workflow execution completes successfully */
  WORKFLOW_END = 'workflow:end',
  /** Emitted when workflow encounters fatal error */
  WORKFLOW_ERROR = 'workflow:error',

  // Node events (individual node lifecycle)
  /** Emitted when a node begins execution */
  NODE_START = 'node:start',
  /** Emitted when a node finishes execution */
  NODE_END = 'node:end',
  /** Emitted when a node encounters error */
  NODE_ERROR = 'node:error',
  /** Emitted when a node completes (alias for NODE_END) */
  NODE_COMPLETE = 'node:complete',

  // Stream data types (LangGraph stream modes)
  /** Values mode: Complete state snapshots */
  VALUES = 'values',
  /** Updates mode: Partial state updates */
  UPDATES = 'updates',
  /** Messages mode: Message streaming */
  MESSAGES = 'messages',
  /** Events mode: Event stream */
  EVENTS = 'events',
  /** Debug mode: Debugging information */
  DEBUG = 'debug',
  /** Final mode: Final output only */
  FINAL = 'final',

  // Progress events
  /** Generic progress update (percentage, status) */
  PROGRESS = 'progress',
  /** Milestone achieved (significant workflow step) */
  MILESTONE = 'milestone',

  // Token events (LLM token streaming)
  /** Individual token from LLM response */
  TOKEN = 'token',

  // Error events
  /** Generic error event */
  ERROR = 'error',

  // Custom events (application-specific)
  /** Custom application event */
  CUSTOM = 'custom',

  // LangGraph Stream Mode Events
  /** LLM token streaming event (streamMode: 'messages') */
  MESSAGE_STREAM = 'message-stream',
  /** Custom progress event (streamMode: 'custom') */
  CUSTOM_STREAM = 'custom-stream',
  /** Debug execution trace (streamMode: 'debug', dev mode only) */
  DEBUG_STREAM = 'debug-stream',
}

// =============================================================================
// Core Interfaces
// =============================================================================

/**
 * Metadata associated with every stream event.
 *
 * @remarks
 * - `timestamp`: ISO 8601 date from backend
 * - `sequenceNumber`: Monotonically increasing integer for event ordering
 * - `executionId`: Unique identifier for workflow execution session
 * - `nodeId`: Canonical node ID in format: `{domain}/{phase}/{activity}/{detail}`
 *
 * @public
 */
export interface StreamMetadata {
  /** Event timestamp (ISO 8601 from backend) */
  timestamp: Date;
  /** Monotonically increasing sequence number for event ordering */
  sequenceNumber: number;
  /** Unique execution ID for this workflow run */
  executionId: string;
  /** Optional canonical node ID (format: domain/phase/activity/detail) */
  nodeId?: string;
  /** Optional agent type classifier */
  agentType?: string;

  // Node ID components (parsed from canonical node ID)
  /** Domain component from nodeId */
  domain?: string;
  /** Phase component from nodeId */
  phase?: string;
  /** Activity component from nodeId */
  activity?: string;
  /** Detail component from nodeId */
  detail?: string;

  /** Allow additional metadata fields from backend */
  [key: string]: unknown;
}

/**
 * Generic stream event structure with type discrimination.
 *
 * @typeParam T - Type of event data payload (defaults to `unknown` for runtime safety)
 *
 * @remarks
 * Use type guards (`isWorkflowEvent`, `isNodeEvent`, etc.) for narrowing
 * the event type and accessing type-specific data.
 *
 * @public
 */
export interface StreamUpdate<T = unknown> {
  /** Event type discriminator (use for narrowing) */
  type: StreamEventType;
  /** Event-specific data payload (type varies by event type) */
  data: T;
  /** Optional metadata (always present from backend) */
  metadata?: StreamMetadata;
}

/**
 * Specialized interface for token streaming events from LLM responses.
 *
 * @remarks
 * High-frequency events (10-100+ per second) emitted for each token
 * generated by LLM during content creation.
 *
 * @public
 */
export interface TokenUpdate {
  /** Individual token string from LLM */
  token: string;
  /** Optional execution ID for token correlation */
  executionId?: string;
  /** Optional node ID for source tracking */
  nodeId?: string;
}

// =============================================================================
// LangGraph Streaming Event Interfaces
// =============================================================================

/**
 * LLM token streaming event emitted when LLM generates tokens in real-time.
 * Corresponds to LangGraph 'messages' stream mode.
 *
 * @remarks
 * Emitted for each token/chunk generated by LLM nodes.
 * Used for real-time display of agent responses.
 *
 * @public
 */
export interface MessageStreamEvent {
  /** Event type discriminator */
  readonly type: 'message-stream';
  /** Workflow execution ID */
  readonly executionId: string;
  /** Node that emitted this message chunk */
  readonly nodeName: string;
  /** Execution step number */
  readonly step: number;
  /** The token/chunk content (extracted from messageChunk) */
  readonly content: string;
  /** Optional AI message chunk structure */
  readonly messageChunk?: {
    readonly id: string;
    readonly type: string;
    readonly content: string;
    readonly additional_kwargs?: Record<string, unknown>;
  };
  /** Event timestamp (ISO 8601) */
  readonly timestamp: string;
  /** LangGraph execution metadata */
  readonly metadata?: {
    readonly langgraph_node: string;
    readonly langgraph_step: number;
    readonly langgraph_triggers?: readonly string[];
    readonly langgraph_path?: readonly string[];
    readonly [key: string]: unknown;
  };
}

/**
 * Custom progress event emitted for user-defined agent progress tracking.
 * Corresponds to LangGraph 'custom' stream mode.
 *
 * @remarks
 * Emitted by agents for custom progress/metrics reporting.
 * Flexible data structure for application-specific needs.
 *
 * @public
 */
export interface CustomStreamEvent {
  /** Event type discriminator */
  readonly type: 'custom-stream';
  /** Workflow execution ID */
  readonly executionId: string;
  /** Custom progress data (flexible structure) */
  readonly data: {
    readonly agent?: string;
    readonly stage?: string;
    readonly message?: string;
    readonly percentage?: number;
    readonly [key: string]: unknown;
  };
  /** Event timestamp (ISO 8601) */
  readonly timestamp: string;
}

/**
 * Debug execution trace event emitted in development mode.
 * Corresponds to LangGraph 'debug' stream mode.
 *
 * @remarks
 * Only emitted when `NODE_ENV === 'development'`.
 * Provides detailed execution traces for debugging workflows.
 *
 * @public
 */
export interface DebugStreamEvent {
  /** Event type discriminator */
  readonly type: 'debug-stream';
  /** Workflow execution ID */
  readonly executionId: string;
  /** Debug event type */
  readonly eventType: 'task' | 'task_result' | 'checkpoint';
  /** Task identifier */
  readonly taskId?: string;
  /** Task name */
  readonly taskName?: string;
  /** Debug payload with task/checkpoint details */
  readonly payload?: {
    readonly id: string;
    readonly name: string;
    readonly input?: unknown;
    readonly output?: unknown;
    readonly error?: unknown;
    readonly [key: string]: unknown;
  };
  /** Event timestamp (ISO 8601) */
  readonly timestamp: string;
  /** Execution step number */
  readonly step?: number;
}

/**
 * Error structure for SSE connection and stream processing errors.
 *
 * @remarks
 * Renamed from POC's `WebSocketError` to reflect the SSE transport.
 * - `sse_error`: SSE connection/transport errors
 * - `validation_error`: Zod schema validation failures
 * - `connection_error`: Network/connectivity issues
 *
 * @public
 */
export interface StreamError {
  /** Error category */
  type: 'sse_error' | 'validation_error' | 'connection_error';
  /** Human-readable error message */
  message: string;
  /** Error occurrence timestamp */
  timestamp: Date;
  /** Optional additional error details */
  details?: unknown;
}

/**
 * Represents the actual JSON payload structure received from SSE.
 * Covers all backend domain event types plus workflow_complete.
 *
 * @remarks
 * This is the unified type for ALL events coming through SSE.
 * The `type` field discriminates which handler processes the event.
 *
 * @public
 */
export interface DomainEvent {
  readonly type:
    | 'workflow-update'
    | 'tool-execution'
    | 'message-stream'
    | 'custom-stream'
    | 'workflow_complete';
  readonly executionId: string;
  readonly timestamp: string;

  /** Node name from LangGraph */
  readonly nodeName?: string;

  /** State snapshot for workflow-update events */
  readonly state?: Record<string, unknown>;

  /** LangGraph execution metadata */
  readonly metadata?: {
    readonly isSystemNode?: boolean;
    readonly isToolNode?: boolean;
    readonly isEmpty?: boolean;
    readonly isSubgraphEvent?: boolean;
    readonly subgraphId?: string;
    readonly namespacePath?: readonly string[];
    readonly langgraph_node?: string;
    readonly langgraph_step?: number;
    readonly langgraph_checkpoint_ns?: string;
    readonly checkpoint_ns?: string;
    readonly [key: string]: unknown;
  };

  /** Token content for message-stream events */
  readonly content?: string;

  /** Execution step number for message-stream events */
  readonly step?: number;

  /** AI message chunk for message-stream events */
  readonly messageChunk?: {
    readonly id?: string;
    readonly type?: string;
    readonly content?: string;
    readonly tool_call_chunks?: ReadonlyArray<{
      readonly name?: string;
      readonly args?: string;
      readonly id?: string;
      readonly index?: number;
    }>;
    readonly tool_calls?: ReadonlyArray<{
      readonly name: string;
      readonly args: Record<string, unknown>;
      readonly id: string;
    }>;
    readonly additional_kwargs?: Record<string, unknown>;
    readonly response_metadata?: Record<string, unknown>;
  };

  /** Tool execution data for tool-execution events */
  readonly toolData?: Record<string, unknown>;

  /** Custom data for custom-stream events */
  readonly data?: Record<string, unknown>;
}

// =============================================================================
// Zod Schemas for Runtime Validation
// =============================================================================

/**
 * Zod schema for `StreamMetadata` runtime validation.
 *
 * @remarks
 * Coerces timestamp string to Date object. Uses `passthrough()`
 * to allow additional backend fields.
 *
 * @public
 */
export const StreamMetadataSchema = z
  .object({
    timestamp: z.coerce.date(),
    sequenceNumber: z.number(),
    executionId: z.string(),
    nodeId: z.string().optional(),
    agentType: z.string().optional(),
    domain: z.string().optional(),
    phase: z.string().optional(),
    activity: z.string().optional(),
    detail: z.string().optional(),
  })
  .passthrough();

/**
 * Zod schema for `StreamUpdate` runtime validation.
 *
 * @remarks
 * Uses `z.nativeEnum` for `StreamEventType` validation.
 * Data field is `z.unknown()` for flexible payload types.
 *
 * @public
 */
export const StreamUpdateSchema = z.object({
  type: z.nativeEnum(StreamEventType),
  data: z.unknown(),
  metadata: StreamMetadataSchema.optional(),
});

/**
 * Zod schema for `TokenUpdate` runtime validation.
 *
 * @public
 */
export const TokenUpdateSchema = z.object({
  token: z.string(),
  executionId: z.string().optional(),
  nodeId: z.string().optional(),
});

/**
 * Zod schema for `StreamError` runtime validation.
 *
 * @remarks
 * Renamed from POC's `WebSocketErrorSchema` to match SSE transport.
 *
 * @public
 */
export const StreamErrorSchema = z.object({
  type: z.enum(['sse_error', 'validation_error', 'connection_error']),
  message: z.string(),
  timestamp: z.coerce.date(),
  details: z.unknown().optional(),
});

/**
 * Zod schema for `MessageStreamEvent` runtime validation.
 *
 * @remarks
 * Validates LLM token streaming events from backend.
 * Ensures type-safe handling of message chunks.
 *
 * @public
 */
export const MessageStreamEventSchema = z.object({
  type: z.literal('message-stream'),
  executionId: z.string(),
  nodeName: z.string(),
  step: z.number(),
  content: z.string(),
  messageChunk: z
    .object({
      id: z.string(),
      type: z.string(),
      content: z.string(),
      additional_kwargs: z.record(z.unknown()).optional(),
    })
    .optional(),
  timestamp: z.string(),
  metadata: z
    .object({
      langgraph_node: z.string(),
      langgraph_step: z.number(),
      langgraph_triggers: z.array(z.string()).optional(),
      langgraph_path: z.array(z.string()).optional(),
    })
    .passthrough()
    .optional(),
});

/**
 * Zod schema for `CustomStreamEvent` runtime validation.
 *
 * @remarks
 * Validates custom progress events from backend.
 * Flexible data structure with common fields.
 *
 * @public
 */
export const CustomStreamEventSchema = z.object({
  type: z.literal('custom-stream'),
  executionId: z.string(),
  data: z
    .object({
      agent: z.string().optional(),
      stage: z.string().optional(),
      message: z.string().optional(),
      percentage: z.number().min(0).max(100).optional(),
    })
    .passthrough(),
  timestamp: z.string(),
});

/**
 * Zod schema for `DebugStreamEvent` runtime validation.
 *
 * @remarks
 * Validates debug trace events from backend.
 * Only present in development mode.
 *
 * @public
 */
export const DebugStreamEventSchema = z.object({
  type: z.literal('debug-stream'),
  executionId: z.string(),
  eventType: z.enum(['task', 'task_result', 'checkpoint']),
  taskId: z.string().optional(),
  taskName: z.string().optional(),
  payload: z
    .object({
      id: z.string(),
      name: z.string(),
      input: z.unknown().optional(),
      output: z.unknown().optional(),
      error: z.unknown().optional(),
    })
    .passthrough()
    .optional(),
  timestamp: z.string(),
  step: z.number().optional(),
});

// =============================================================================
// Type Guards for Discriminated Union Narrowing
// =============================================================================

/**
 * Type guard for workflow lifecycle events.
 *
 * @param event - Stream event to check
 * @returns `true` if event is a workflow lifecycle event
 *   (`workflow:start`, `workflow:end`, or `workflow:error`)
 *
 * @public
 */
export function isWorkflowEvent(event: StreamUpdate): boolean {
  return (
    event.type === StreamEventType.WORKFLOW_START ||
    event.type === StreamEventType.WORKFLOW_END ||
    event.type === StreamEventType.WORKFLOW_ERROR
  );
}

/**
 * Type guard for node lifecycle events.
 *
 * @param event - Stream event to check
 * @returns `true` if event is a node lifecycle event
 *
 * @public
 */
export function isNodeEvent(event: StreamUpdate): boolean {
  return (
    event.type === StreamEventType.NODE_START ||
    event.type === StreamEventType.NODE_END ||
    event.type === StreamEventType.NODE_ERROR ||
    event.type === StreamEventType.NODE_COMPLETE
  );
}

/**
 * Type guard for progress tracking events.
 *
 * @param event - Stream event to check
 * @returns `true` if event is a progress tracking event
 *
 * @public
 */
export function isProgressEvent(event: StreamUpdate): boolean {
  return (
    event.type === StreamEventType.PROGRESS ||
    event.type === StreamEventType.MILESTONE
  );
}

/**
 * Type guard for token streaming events.
 *
 * @param event - Stream event to check
 * @returns `true` if event is a token streaming event
 *
 * @public
 */
export function isTokenEvent(event: StreamUpdate): boolean {
  return event.type === StreamEventType.TOKEN;
}

/**
 * Type guard for error events (generic, node, and workflow errors).
 *
 * @param event - Stream event to check
 * @returns `true` if event is any error event
 *
 * @public
 */
export function isErrorEvent(event: StreamUpdate): boolean {
  return (
    event.type === StreamEventType.ERROR ||
    event.type === StreamEventType.NODE_ERROR ||
    event.type === StreamEventType.WORKFLOW_ERROR
  );
}

/**
 * Type guard for stream data type events (LangGraph stream modes).
 *
 * @param event - Stream event to check
 * @returns `true` if event is a stream data type event
 *
 * @public
 */
export function isStreamDataEvent(event: StreamUpdate): boolean {
  return (
    event.type === StreamEventType.VALUES ||
    event.type === StreamEventType.UPDATES ||
    event.type === StreamEventType.MESSAGES ||
    event.type === StreamEventType.EVENTS ||
    event.type === StreamEventType.DEBUG ||
    event.type === StreamEventType.FINAL
  );
}

/**
 * Type guard for agent-related events (events with `agentType` metadata).
 *
 * @param event - Stream event to check
 * @returns `true` if event has `agentType` in metadata
 *
 * @public
 */
export function isAgentEvent(event: StreamUpdate): boolean {
  return event.metadata?.agentType !== undefined;
}

/**
 * Type guard for a specific agent type.
 *
 * @param event - Stream event to check
 * @param agentType - Agent type to match
 * @returns `true` if event is from specified agent
 *
 * @public
 */
export function isAgentTypeEvent(
  event: StreamUpdate,
  agentType: string
): boolean {
  return event.metadata?.agentType === agentType;
}

/**
 * Type guard for node-specific events (events with `nodeId` metadata).
 *
 * @param event - Stream event to check
 * @returns `true` if event has `nodeId` in metadata
 *
 * @public
 */
export function hasNodeId(event: StreamUpdate): boolean {
  return event.metadata?.nodeId !== undefined;
}

/**
 * Type guard for message stream events (LLM token streaming).
 *
 * @param event - Event to check
 * @returns `true` if event is a `MessageStreamEvent`
 *
 * @public
 */
export function isMessageStreamEvent(
  event:
    | StreamUpdate
    | MessageStreamEvent
    | CustomStreamEvent
    | DebugStreamEvent
): event is MessageStreamEvent {
  return (
    typeof event === 'object' &&
    event !== null &&
    'type' in event &&
    event.type === 'message-stream'
  );
}

/**
 * Type guard for custom progress events.
 *
 * @param event - Event to check
 * @returns `true` if event is a `CustomStreamEvent`
 *
 * @public
 */
export function isCustomStreamEvent(
  event:
    | StreamUpdate
    | MessageStreamEvent
    | CustomStreamEvent
    | DebugStreamEvent
): event is CustomStreamEvent {
  return (
    typeof event === 'object' &&
    event !== null &&
    'type' in event &&
    event.type === 'custom-stream'
  );
}

/**
 * Type guard for debug trace events.
 *
 * @param event - Event to check
 * @returns `true` if event is a `DebugStreamEvent`
 *
 * @public
 */
export function isDebugStreamEvent(
  event:
    | StreamUpdate
    | MessageStreamEvent
    | CustomStreamEvent
    | DebugStreamEvent
): event is DebugStreamEvent {
  return (
    typeof event === 'object' &&
    event !== null &&
    'type' in event &&
    event.type === 'debug-stream'
  );
}

// =============================================================================
// Utility Functions
// =============================================================================

/**
 * Parses a canonical node ID into its component parts.
 *
 * @param nodeId - Canonical node ID (format: `domain/phase/activity/detail`)
 * @returns Object with `domain`, `phase`, `activity`, `detail` components
 *
 * @remarks
 * This is a generic utility that does not contain any domain-specific mappings.
 * For domain-specific node-to-agent mapping, use the `nodeIdMapper` callback
 * in `LangGraphConfig`.
 *
 * @example
 * ```typescript
 * const parts = parseNodeId('myapp/data-processing/transformer/validate');
 * // { domain: 'myapp', phase: 'data-processing', activity: 'transformer', detail: 'validate' }
 * ```
 *
 * @public
 */
export function parseNodeId(nodeId: string): {
  domain?: string;
  phase?: string;
  activity?: string;
  detail?: string;
} {
  const parts = nodeId.split('/');

  return {
    domain: parts[0] || undefined,
    phase: parts[1] || undefined,
    activity: parts[2] || undefined,
    detail: parts[3] || undefined,
  };
}
