import { SetMetadata, Injectable } from '@nestjs/common';
import {
  DECORATOR_METADATA_KEYS,
  type RepositoryConfig,
  type QueryExecutionOptions,
} from './decorator-metadata.interface';

/**
 * Configuration for the @Neo4jRepository decorator
 */
export interface Neo4jRepositoryConfig {
  /** Entity type this repository manages */
  entityType: () => any;
  /** Neo4j label for the entity */
  label?: string;
  /** Custom connection name */
  connectionName?: string;
  /** Default query options for all operations */
  defaultOptions?: QueryExecutionOptions;
  /** Description for documentation */
  description?: string;
  /** Tags for categorization */
  tags?: string[];
  /** Whether to auto-generate CRUD methods */
  autoGenerate?: boolean;
}

/**
 *  @Neo4jRepository decorator for repository pattern implementation
 *
 * Features:
 * - Auto-generation of basic CRUD operations
 * - Type-safe entity management
 * - Connection management
 * - Default query options inheritance
 * - Automatic dependency injection setup
 *
 * @example
 * ```typescript
 * @Neo4jRepository({
 *   entityType: () => User,
 *   label: 'User',
 *   autoGenerate: true,
 *   defaultOptions: {
 *     cache: { enabled: true, ttl: 300000 }
 *   }
 * })
 * export class UserRepository {
 *   // Auto-generated methods:
 *   // - findById(id: string): Promise<User | null>
 *   // - findAll(options?: FindOptions): Promise<User[]>
 *   // - create(data: Partial<User>): Promise<User>
 *   // - update(id: string, updates: Partial<User>): Promise<User>
 *   // - delete(id: string): Promise<boolean>
 *
 *   @CypherQuery<User[]>({ ... })
 *   async findByEmail(email: string): Promise<User[]> {
 *     // Custom query method
 *   }
 * }
 * ```
 */
export function Neo4jRepository(config: Neo4jRepositoryConfig): ClassDecorator {
  return function (constructor: any) {
    // Validate configuration
    validateRepositoryConfig(config);

    // Extract entity information
    const entityType = config.entityType();
    const label = config.label || getEntityLabel(entityType);

    // Create repository metadata
    const metadata: RepositoryConfig = {
      id: `Repository:${constructor.name}`,
      entityType: config.entityType,
      label,
      connectionName: config.connectionName,
      defaultOptions: config.defaultOptions,
      description: config.description || `Repository for ${label} entities`,
      tags: config.tags || ['repository', label.toLowerCase()],
      enabled: true,
    };

    // Set metadata on the class
    SetMetadata(DECORATOR_METADATA_KEYS.REPOSITORY, metadata)(constructor);

    // Apply @Injectable decorator for dependency injection
    Injectable()(constructor);

    // Auto-generate CRUD methods if requested
    if (config.autoGenerate !== false) {
      addAutoGeneratedMethods(constructor, metadata);
    }

    // Enhance constructor to inject Neo4j service
    const newConstructor = class extends constructor {
      protected neo4jService: any;
      protected entityLabel: string = label;
      protected defaultOptions: QueryExecutionOptions =
        config.defaultOptions || {};

      constructor(...args: any[]) {
        super(...args);

        // Find and inject Neo4j service from arguments
        this.neo4jService = this.findNeo4jService(args);

        if (!this.neo4jService) {
          throw new Error(
            `Neo4j service not found in ${constructor.name}. ` +
              'Ensure Neo4jService or Neo4jService is injected in the constructor.'
          );
        }
      }

      /**
       * Find Neo4j service instance from constructor arguments
       */
      private findNeo4jService(args: any[]): any {
        return args.find(
          (arg) =>
            arg &&
            (typeof arg.run === 'function' ||
              typeof arg.run === 'function')
        );
      }

      /**
       * Get the Neo4j service instance
       */
      protected getNeo4jService(): any {
        return this.neo4jService;
      }

      /**
       * Execute query with repository defaults
       */
      protected async executeQuery<T>(
        query: string,
        params?: Record<string, any>,
        options?: QueryExecutionOptions
      ): Promise<T> {
        const mergedOptions = { ...this.defaultOptions, ...options };

        if (typeof this.neo4jService.run === 'function') {
          const result = await this.neo4jService.run(
            query,
            params,
            mergedOptions
          );
          return result.records;
        } else {
          const result = await this.neo4jService.run(
            query,
            params,
            mergedOptions
          );
          return result.records || result;
        }
      }
    };

    // Preserve original class name and metadata
    Object.defineProperty(newConstructor, 'name', {
      value: constructor.name,
    });

    return newConstructor as any;
  };
}

/**
 * Simplified @Repository decorator
 */
export function Repository(entityType: () => any): ClassDecorator {
  return Neo4jRepository({
    entityType,
    autoGenerate: true,
  });
}

/**
 * Add auto-generated CRUD methods to the repository class
 */
function addAutoGeneratedMethods(
  constructor: any,
  metadata: RepositoryConfig
): void {
  const prototype = constructor.prototype;
  const label = metadata.label!;

  // Auto-generate findById method
  if (!prototype.findById) {
    prototype.findById = async function (id: string): Promise<any> {
      const query = `MATCH (n:${label} {id: $id}) RETURN n LIMIT 1`;
      const result = await this.executeQuery(query, { id });
      return result.length > 0 ? result[0] : null;
    };
  }

  // Auto-generate findAll method
  if (!prototype.findAll) {
    prototype.findAll = async function (
      options?: FindAllOptions
    ): Promise<any[]> {
      let query = `MATCH (n:${label})`;
      const params: Record<string, any> = {};

      // Add where clause if conditions provided
      if (options?.where) {
        const whereConditions = Object.entries(options.where)
          .map(([key, value]) => {
            params[key] = value;
            return `n.${key} = $${key}`;
          })
          .join(' AND ');
        query += ` WHERE ${whereConditions}`;
      }

      query += ' RETURN n';

      // Add ordering
      if (options?.orderBy) {
        const orderClause = Object.entries(options.orderBy)
          .map(([field, direction]) => `n.${field} ${direction}`)
          .join(', ');
        query += ` ORDER BY ${orderClause}`;
      }

      // Add pagination
      if (options?.limit) {
        query += ` LIMIT ${options.limit}`;
        if (options.offset) {
          query += ` SKIP ${options.offset}`;
        }
      }

      return this.executeQuery(query, params);
    };
  }

  // Auto-generate create method
  if (!prototype.create) {
    prototype.create = async function (
      data: Record<string, any>
    ): Promise<any> {
      // Generate ID if not provided
      if (!data.id) {
        data.id = generateId();
      }

      const query = `CREATE (n:${label} $data) RETURN n`;
      const result = await this.executeQuery(
        query,
        { data },
        { accessMode: 'WRITE' }
      );
      return result[0];
    };
  }

  // Auto-generate update method
  if (!prototype.update) {
    prototype.update = async function (
      id: string,
      updates: Record<string, any>
    ): Promise<any> {
      const query = `MATCH (n:${label} {id: $id}) SET n += $updates RETURN n`;
      const result = await this.executeQuery(
        query,
        { id, updates },
        { accessMode: 'WRITE' }
      );
      return result.length > 0 ? result[0] : null;
    };
  }

  // Auto-generate delete method
  if (!prototype.delete) {
    prototype.delete = async function (id: string): Promise<boolean> {
      const query = `MATCH (n:${label} {id: $id}) DELETE n RETURN count(n) > 0 as deleted`;
      const result = await this.executeQuery(
        query,
        { id },
        { accessMode: 'WRITE' }
      );
      return result[0]?.deleted || false;
    };
  }

  // Auto-generate count method
  if (!prototype.count) {
    prototype.count = async function (
      where?: Record<string, any>
    ): Promise<number> {
      let query = `MATCH (n:${label})`;
      const params: Record<string, any> = {};

      if (where) {
        const whereConditions = Object.entries(where)
          .map(([key, value]) => {
            params[key] = value;
            return `n.${key} = $${key}`;
          })
          .join(' AND ');
        query += ` WHERE ${whereConditions}`;
      }

      query += ' RETURN count(n) as count';

      const result = await this.executeQuery(query, params);
      return result[0]?.count || 0;
    };
  }

  // Auto-generate exists method
  if (!prototype.exists) {
    prototype.exists = async function (id: string): Promise<boolean> {
      const query = `MATCH (n:${label} {id: $id}) RETURN count(n) > 0 as exists`;
      const result = await this.executeQuery(query, { id });
      return result[0]?.exists || false;
    };
  }
}

/**
 * Options for findAll method
 */
export interface FindAllOptions {
  where?: Record<string, any>;
  orderBy?: Record<string, 'ASC' | 'DESC'>;
  limit?: number;
  offset?: number;
}

/**
 * Validate repository configuration
 */
function validateRepositoryConfig(config: Neo4jRepositoryConfig): void {
  if (!config.entityType || typeof config.entityType !== 'function') {
    throw new Error(
      'Neo4jRepository decorator requires a valid entityType function'
    );
  }

  try {
    config.entityType();
  } catch (error) {
    throw new Error('Neo4jRepository entityType function must be callable');
  }
}

/**
 * Get entity label from entity type
 */
function getEntityLabel(entityType: any): string {
  if (typeof entityType === 'function') {
    return entityType.name || 'Entity';
  }

  if (entityType && typeof entityType === 'object') {
    return entityType.constructor?.name || 'Entity';
  }

  return 'Entity';
}

/**
 * Generate a unique ID for new entities
 */
function generateId(): string {
  return `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
}
